<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BookedServicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('booked_services')->delete();
        
        \DB::table('booked_services')->insert(array (
            0 => 
            array (
                'id' => 1,
                'patient_id' => 50,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 11,
                'date' => '2024-09-26T10:48:37.984Z',
                'price' => 30.0,
                'is_paid' => 0,
                'fund_id' => 33,
                'question' => 'fytutyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-09-26 15:49:07',
                'updated_at' => '2024-09-26 15:49:07',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'patient_id' => 59,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 10,
                'date' => '2024-09-27T14:00:30.907Z',
                'price' => 30.0,
                'is_paid' => 0,
                'fund_id' => 45,
                'question' => 'test q',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-09-27 19:01:17',
                'updated_at' => '2024-09-27 19:01:17',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'patient_id' => 59,
                'doctor_id' => 60,
                'clinic_id' => NULL,
                'service_id' => 8,
                'date' => '2024-09-27T14:02:20.669Z',
                'price' => 20.0,
                'is_paid' => 1,
                'fund_id' => 46,
                'question' => 'teast',
                'attachment_url' => NULL,
                'service_status_code' => 5,
                'started_at' => NULL,
                'ended_at' => '2024-10-04 18:20:44',
                'created_at' => '2024-09-27 19:02:47',
                'updated_at' => '2024-10-04 18:20:44',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'patient_id' => 60,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 11,
                'date' => '2024-10-01T09:18:04.026Z',
                'price' => 30.0,
                'is_paid' => 1,
                'fund_id' => 51,
                'question' => NULL,
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-01 14:18:14',
                'updated_at' => '2024-10-01 14:19:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'patient_id' => 60,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 10,
                'date' => '2024-10-01T09:21:12.820Z',
                'price' => 30.0,
                'is_paid' => 1,
                'fund_id' => NULL,
                'question' => NULL,
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-01 14:22:30',
                'updated_at' => '2024-10-01 14:22:30',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'patient_id' => 60,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 10,
                'date' => '2024-10-02T12:13:11.612Z',
                'price' => 30.0,
                'is_paid' => 1,
                'fund_id' => 63,
                'question' => 'what is this',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-02 17:14:56',
                'updated_at' => '2024-10-02 17:15:10',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'patient_id' => 60,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 10,
                'date' => '2024-10-02T12:17:09.362Z',
                'price' => 30.0,
                'is_paid' => 0,
                'fund_id' => 64,
                'question' => 'testy',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-02 17:17:23',
                'updated_at' => '2024-10-02 17:17:23',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'patient_id' => 60,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 10,
                'date' => '2024-10-03T10:22:09.445Z',
                'price' => 30.0,
                'is_paid' => 1,
                'fund_id' => NULL,
                'question' => 'dsfasdfasdfasdfsafasdfsadfsdf',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-03 15:22:24',
                'updated_at' => '2024-10-03 15:22:24',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'patient_id' => 60,
                'doctor_id' => 1,
                'clinic_id' => NULL,
                'service_id' => 2,
                'date' => '2024-10-03T10:48:42.676Z',
                'price' => 20.0,
                'is_paid' => 1,
                'fund_id' => 65,
                'question' => 'asdasd',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-03 15:48:56',
                'updated_at' => '2024-10-03 15:49:28',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'patient_id' => 62,
                'doctor_id' => 1,
                'clinic_id' => NULL,
                'service_id' => 3,
                'date' => '2024-10-03T10:52:34.745Z',
                'price' => 30.0,
                'is_paid' => 0,
                'fund_id' => 66,
                'question' => 'asdasd',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-03 15:52:41',
                'updated_at' => '2024-10-03 15:52:41',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'patient_id' => 63,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 9,
                'date' => '2024-10-03T13:13:29.876Z',
                'price' => 20.0,
                'is_paid' => 1,
                'fund_id' => 70,
                'question' => NULL,
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-03 18:13:53',
                'updated_at' => '2024-10-03 18:14:22',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'patient_id' => 63,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 11,
                'date' => '2024-10-03T13:14:57.503Z',
                'price' => 30.0,
                'is_paid' => 0,
                'fund_id' => 71,
                'question' => NULL,
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-03 18:15:06',
                'updated_at' => '2024-10-03 18:15:06',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'patient_id' => 60,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 11,
                'date' => '2024-10-04T09:41:06.263Z',
                'price' => 30.0,
                'is_paid' => 0,
                'fund_id' => 72,
                'question' => 'asdasd',
                'attachment_url' => NULL,
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-04 14:41:21',
                'updated_at' => '2024-10-04 14:41:21',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'patient_id' => 50,
                'doctor_id' => 60,
                'clinic_id' => NULL,
                'service_id' => 7,
                'date' => '2024-10-04T10:36:48.941Z',
                'price' => 20.0,
                'is_paid' => 1,
                'fund_id' => 73,
                'question' => NULL,
                'attachment_url' => NULL,
                'service_status_code' => 5,
                'started_at' => NULL,
                'ended_at' => '2024-10-04 15:38:57',
                'created_at' => '2024-10-04 15:36:58',
                'updated_at' => '2024-10-04 15:38:57',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'patient_id' => 50,
                'doctor_id' => 1,
                'clinic_id' => NULL,
                'service_id' => 3,
                'date' => '2024-10-04T12:49:42.542Z',
                'price' => 30.0,
                'is_paid' => 0,
                'fund_id' => 74,
                'question' => 'asdasdasd',
                'attachment_url' => NULL,
                'service_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-04 17:49:56',
                'updated_at' => '2024-10-04 17:55:56',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'patient_id' => 50,
                'doctor_id' => 60,
                'clinic_id' => NULL,
                'service_id' => 8,
                'date' => '2024-10-04T13:21:59.971Z',
                'price' => 20.0,
                'is_paid' => 0,
                'fund_id' => 75,
                'question' => 'asdasdasd',
                'attachment_url' => NULL,
                'service_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-04 18:22:12',
                'updated_at' => '2024-10-04 18:22:34',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'patient_id' => 64,
                'doctor_id' => 60,
                'clinic_id' => NULL,
                'service_id' => 6,
                'date' => '2024-10-05T16:56:37.582Z',
                'price' => 20.0,
                'is_paid' => 1,
                'fund_id' => 83,
                'question' => 'HEllo need this service',
                'attachment_url' => NULL,
                'service_status_code' => 2,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-05 21:58:42',
                'updated_at' => '2024-10-05 22:00:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'patient_id' => 65,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 11,
                'date' => '2024-10-07T07:18:09.913Z',
                'price' => 30.0,
                'is_paid' => 1,
                'fund_id' => NULL,
                'question' => 'ghg',
                'attachment_url' => '/files/booked_services/1728285509Screenshot 2024-09-30 at 12.33.48 PM.png',
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-07 12:18:29',
                'updated_at' => '2024-10-07 12:18:29',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'patient_id' => 69,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_id' => 11,
                'date' => '2024-10-07T13:07:15.855Z',
                'price' => 30.0,
                'is_paid' => 1,
                'fund_id' => 92,
                'question' => 'sadasdas',
                'attachment_url' => '/files/booked_services/1728306468Lovepik_com-400195471-hospital.png',
                'service_status_code' => 1,
                'started_at' => NULL,
                'ended_at' => NULL,
                'created_at' => '2024-10-07 18:07:48',
                'updated_at' => '2024-10-07 18:08:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'patient_id' => 69,
                'doctor_id' => 1,
                'clinic_id' => NULL,
                'service_id' => 3,
                'date' => '2024-10-07T13:12:19.833Z',
                'price' => 30.0,
                'is_paid' => 1,
                'fund_id' => 93,
                'question' => NULL,
                'attachment_url' => NULL,
                'service_status_code' => 5,
                'started_at' => NULL,
                'ended_at' => '2024-10-07 18:16:35',
                'created_at' => '2024-10-07 18:12:27',
                'updated_at' => '2024-10-07 18:16:35',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}