<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ClinicReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('clinic_reviews')->delete();
        
        \DB::table('clinic_reviews')->insert(array (
            0 => 
            array (
                'id' => 2,
                'clinic_id' => 21,
                'patient_id' => 54,
                'rating' => 5.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'I recently visited, and my overall experience was [positive/negative]. From the moment I walked in, the staff was [friendly/professional/unwelcoming], which set the tone for the rest of my visit.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 12:52:07',
                'updated_at' => '2024-09-25 12:52:07',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'clinic_id' => 22,
                'patient_id' => 54,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 2.0,
                'service' => 4.0,
                'comment' => 'The clinic is clean, well-organized, modern, etc.. The waiting area was [comfortable/crowded], and I felt [relaxed/rushed] during my time there. They also maintain good hygiene practices, safety measures, etc..',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 12:52:55',
                'updated_at' => '2024-09-25 12:52:55',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'clinic_id' => 23,
                'patient_id' => 54,
                'rating' => 4.0,
                'experience' => 2.0,
                'communication' => 5.0,
                'service' => 4.0,
                'comment' => 'The staff, including the receptionist, nurses, and doctors, were [professional, attentive, or dismissive]. They [clearly communicated, were patient with questions, or rushed through the process].',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 12:53:42',
                'updated_at' => '2024-09-25 12:53:42',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'clinic_id' => 28,
                'patient_id' => 54,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor I saw was [thorough/knowledgeable/unhelpful]. They took the time to [explain the diagnosis, treatment options, listen to concerns, etc.], which made me feel [reassured/confused]. The treatment plan was [effective/unclear].',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 12:54:20',
                'updated_at' => '2024-09-25 12:54:20',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'clinic_id' => 29,
                'patient_id' => 54,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The pricing seemed [reasonable/expensive], and the clinic [worked seamlessly with my insurance/had issues with insurance claims]. They were [transparent/unclear] about the costs beforehand.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 12:54:59',
                'updated_at' => '2024-09-25 12:54:59',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'clinic_id' => 30,
                'patient_id' => 54,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I recently visited , and I was impressed with the entire experience. The clinic was spotless, and the staff was warm and welcoming.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 12:55:42',
                'updated_at' => '2024-09-25 12:55:42',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'clinic_id' => 30,
                'patient_id' => 55,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 5.0,
                'service' => 4.0,
                'comment' => 'My experience at  was disappointing. The clinic was overcrowded, and the waiting area felt cramped. I waited for over [time] despite having a scheduled appointment.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 12:59:33',
                'updated_at' => '2024-09-25 12:59:33',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'clinic_id' => 29,
                'patient_id' => 55,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'he staff at the front desk seemed overwhelmed and disorganized, which added to the frustration. When I finally saw Dr. [Name], they were hurried and didn’t seem to fully listen to my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:00:00',
                'updated_at' => '2024-09-25 13:00:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'clinic_id' => 23,
                'patient_id' => 55,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I had a great experience at  under the care of Dr. [Specialist’s Name]. I was referred here for a specific issue, and I couldn’t be happier with the level of expertise I received',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:00:42',
                'updated_at' => '2024-09-25 13:00:42',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'clinic_id' => 22,
                'patient_id' => 55,
                'rating' => 5.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 5.0,
                'comment' => 'The doctor explained my condition in a way that was easy to understand and offered multiple treatment options, clearly outlining the pros and cons of each.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:01:15',
                'updated_at' => '2024-09-25 13:01:15',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'clinic_id' => 21,
                'patient_id' => 55,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'If you’re looking for quick and efficient care, is the place to go. I walked in without an appointment, and within short amount of time, I was already being attended to.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:02:12',
                'updated_at' => '2024-09-25 13:02:12',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'clinic_id' => 30,
                'patient_id' => 56,
                'rating' => 3.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The staff are extremely organized, and everything from check-in to seeing the doctor went smoothly. Dr. Name was kind, took time to answer my questions',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:05:05',
                'updated_at' => '2024-09-25 13:05:05',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'clinic_id' => 29,
                'patient_id' => 56,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I also appreciated that they follow up to make sure everything is going well after the visit. This is a fantastic clinic for anyone in need of fast, quality medical care.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:06:13',
                'updated_at' => '2024-09-25 13:06:13',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'clinic_id' => 23,
                'patient_id' => 56,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I’ve been a patient at for over , and the care I’ve received has consistently been exceptional. From regular checkups to more complex treatments',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:07:11',
                'updated_at' => '2024-09-25 13:07:11',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'clinic_id' => 22,
                'patient_id' => 56,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'My family and I have been visiting [Clinic Name] for years, and it’s been our go-to for all our healthcare needs. They’re fantastic with both adults and children, and the pediatrician',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:08:25',
                'updated_at' => '2024-09-25 13:08:25',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'clinic_id' => 21,
                'patient_id' => 56,
                'rating' => 2.0,
                'experience' => 3.0,
                'communication' => 2.0,
                'service' => 3.0,
                'comment' => 'I had an urgent medical issue and visited  without an appointment. Despite it being a busy day, the clinic managed to accommodate me fairly quickly.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:09:21',
                'updated_at' => '2024-09-25 13:09:21',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'clinic_id' => 30,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'They were not only quick but also thorough in explaining the issue and starting treatment right away. The efficiency and accuracy of the care I received were impressive',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:13:58',
                'updated_at' => '2024-09-25 13:13:58',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'clinic_id' => 29,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 4.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I’m incredibly grateful for how fast they helped me recover. I would recommend [Clinic Name] to anyone seeking quick and effective treatment.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:16:33',
                'updated_at' => '2024-09-25 13:16:33',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'clinic_id' => 23,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I had to visit  for an emergency, and the care I received was outstanding. I was in pain and needed immediate attention, and the clinic didn’t disappoint',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:17:30',
                'updated_at' => '2024-09-25 13:17:30',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'clinic_id' => 22,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'They accurately diagnosed the issue and began treatment right away. The team worked quickly and efficiently,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:18:31',
                'updated_at' => '2024-09-25 13:18:31',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'clinic_id' => 21,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I had an urgent medical issue and visited  without an appointment. Despite it being a busy day, the clinic managed to accommodate me fairly quickly.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-25 13:19:05',
                'updated_at' => '2024-09-25 13:19:05',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}