<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ClinicSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('clinic_settings')->delete();
        
        \DB::table('clinic_settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'clinic_id' => 27,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            1 => 
            array (
                'id' => 2,
                'clinic_id' => 27,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            2 => 
            array (
                'id' => 3,
                'clinic_id' => 27,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            3 => 
            array (
                'id' => 4,
                'clinic_id' => 27,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            4 => 
            array (
                'id' => 5,
                'clinic_id' => 27,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            5 => 
            array (
                'id' => 6,
                'clinic_id' => 27,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            6 => 
            array (
                'id' => 7,
                'clinic_id' => 27,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            7 => 
            array (
                'id' => 8,
                'clinic_id' => 27,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            8 => 
            array (
                'id' => 9,
                'clinic_id' => 27,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:09:34',
                'updated_at' => '2024-09-16 15:09:34',
            ),
            9 => 
            array (
                'id' => 10,
                'clinic_id' => 28,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            10 => 
            array (
                'id' => 11,
                'clinic_id' => 28,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            11 => 
            array (
                'id' => 12,
                'clinic_id' => 28,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            12 => 
            array (
                'id' => 13,
                'clinic_id' => 28,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            13 => 
            array (
                'id' => 14,
                'clinic_id' => 28,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            14 => 
            array (
                'id' => 15,
                'clinic_id' => 28,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            15 => 
            array (
                'id' => 16,
                'clinic_id' => 28,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            16 => 
            array (
                'id' => 17,
                'clinic_id' => 28,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            17 => 
            array (
                'id' => 18,
                'clinic_id' => 28,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:18:07',
                'updated_at' => '2024-09-16 15:18:07',
            ),
            18 => 
            array (
                'id' => 19,
                'clinic_id' => 29,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:23:39',
                'updated_at' => '2024-09-16 15:23:39',
            ),
            19 => 
            array (
                'id' => 20,
                'clinic_id' => 29,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            20 => 
            array (
                'id' => 21,
                'clinic_id' => 29,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            21 => 
            array (
                'id' => 22,
                'clinic_id' => 29,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            22 => 
            array (
                'id' => 23,
                'clinic_id' => 29,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            23 => 
            array (
                'id' => 24,
                'clinic_id' => 29,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            24 => 
            array (
                'id' => 25,
                'clinic_id' => 29,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapcaht.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            25 => 
            array (
                'id' => 26,
                'clinic_id' => 29,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            26 => 
            array (
                'id' => 27,
                'clinic_id' => 29,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:52:08',
                'updated_at' => '2024-09-16 18:52:08',
            ),
            27 => 
            array (
                'id' => 28,
                'clinic_id' => 30,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 15:39:54',
                'updated_at' => '2024-09-16 15:39:54',
            ),
            28 => 
            array (
                'id' => 29,
                'clinic_id' => 30,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            29 => 
            array (
                'id' => 30,
                'clinic_id' => 30,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            30 => 
            array (
                'id' => 31,
                'clinic_id' => 30,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            31 => 
            array (
                'id' => 32,
                'clinic_id' => 30,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            32 => 
            array (
                'id' => 33,
                'clinic_id' => 30,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            33 => 
            array (
                'id' => 34,
                'clinic_id' => 30,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            34 => 
            array (
                'id' => 35,
                'clinic_id' => 30,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            35 => 
            array (
                'id' => 36,
                'clinic_id' => 30,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:49:44',
                'updated_at' => '2024-09-16 18:49:44',
            ),
            36 => 
            array (
                'id' => 37,
                'clinic_id' => 23,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            37 => 
            array (
                'id' => 38,
                'clinic_id' => 23,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            38 => 
            array (
                'id' => 39,
                'clinic_id' => 23,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            39 => 
            array (
                'id' => 40,
                'clinic_id' => 23,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'Tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            40 => 
            array (
                'id' => 41,
                'clinic_id' => 23,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            41 => 
            array (
                'id' => 42,
                'clinic_id' => 23,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            42 => 
            array (
                'id' => 43,
                'clinic_id' => 23,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            43 => 
            array (
                'id' => 44,
                'clinic_id' => 23,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            44 => 
            array (
                'id' => 45,
                'clinic_id' => 23,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:17:34',
                'updated_at' => '2024-09-16 18:17:34',
            ),
            45 => 
            array (
                'id' => 46,
                'clinic_id' => 24,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            46 => 
            array (
                'id' => 47,
                'clinic_id' => 24,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            47 => 
            array (
                'id' => 48,
                'clinic_id' => 24,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            48 => 
            array (
                'id' => 49,
                'clinic_id' => 24,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            49 => 
            array (
                'id' => 50,
                'clinic_id' => 24,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            50 => 
            array (
                'id' => 51,
                'clinic_id' => 24,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'Whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            51 => 
            array (
                'id' => 52,
                'clinic_id' => 24,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            52 => 
            array (
                'id' => 53,
                'clinic_id' => 24,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            53 => 
            array (
                'id' => 54,
                'clinic_id' => 24,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'Pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:20:22',
                'updated_at' => '2024-09-16 18:20:22',
            ),
            54 => 
            array (
                'id' => 55,
                'clinic_id' => 25,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            55 => 
            array (
                'id' => 56,
                'clinic_id' => 25,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            56 => 
            array (
                'id' => 57,
                'clinic_id' => 25,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            57 => 
            array (
                'id' => 58,
                'clinic_id' => 25,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            58 => 
            array (
                'id' => 59,
                'clinic_id' => 25,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            59 => 
            array (
                'id' => 60,
                'clinic_id' => 25,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            60 => 
            array (
                'id' => 61,
                'clinic_id' => 25,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            61 => 
            array (
                'id' => 62,
                'clinic_id' => 25,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            62 => 
            array (
                'id' => 63,
                'clinic_id' => 25,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:35:26',
                'updated_at' => '2024-09-16 18:35:26',
            ),
            63 => 
            array (
                'id' => 64,
                'clinic_id' => 22,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            64 => 
            array (
                'id' => 65,
                'clinic_id' => 22,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            65 => 
            array (
                'id' => 66,
                'clinic_id' => 22,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            66 => 
            array (
                'id' => 67,
                'clinic_id' => 22,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            67 => 
            array (
                'id' => 68,
                'clinic_id' => 22,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            68 => 
            array (
                'id' => 69,
                'clinic_id' => 22,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            69 => 
            array (
                'id' => 70,
                'clinic_id' => 22,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            70 => 
            array (
                'id' => 71,
                'clinic_id' => 22,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            71 => 
            array (
                'id' => 72,
                'clinic_id' => 22,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:40:30',
                'updated_at' => '2024-09-16 18:40:30',
            ),
            72 => 
            array (
                'id' => 73,
                'clinic_id' => 21,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            73 => 
            array (
                'id' => 74,
                'clinic_id' => 21,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            74 => 
            array (
                'id' => 75,
                'clinic_id' => 21,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            75 => 
            array (
                'id' => 76,
                'clinic_id' => 21,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            76 => 
            array (
                'id' => 77,
                'clinic_id' => 21,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            77 => 
            array (
                'id' => 78,
                'clinic_id' => 21,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            78 => 
            array (
                'id' => 79,
                'clinic_id' => 21,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            79 => 
            array (
                'id' => 80,
                'clinic_id' => 21,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            80 => 
            array (
                'id' => 81,
                'clinic_id' => 21,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 18:44:35',
                'updated_at' => '2024-09-16 18:44:35',
            ),
            81 => 
            array (
                'id' => 82,
                'clinic_id' => 32,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'fsd',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            82 => 
            array (
                'id' => 83,
                'clinic_id' => 32,
                'name' => 'twitter_url',
                'display_name' => 'Twitter Url',
                'value' => 'sdfgsfdg',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            83 => 
            array (
                'id' => 84,
                'clinic_id' => 32,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'dsfgdsf',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            84 => 
            array (
                'id' => 85,
                'clinic_id' => 32,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'gdsfgdsf',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            85 => 
            array (
                'id' => 86,
                'clinic_id' => 32,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'sdfgfsdg',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            86 => 
            array (
                'id' => 87,
                'clinic_id' => 32,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'dfsgdfs',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            87 => 
            array (
                'id' => 88,
                'clinic_id' => 32,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'dfsgsdf',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            88 => 
            array (
                'id' => 89,
                'clinic_id' => 32,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'dfsgdsf',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
            89 => 
            array (
                'id' => 90,
                'clinic_id' => 32,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'dsfgsdf',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 13:21:51',
                'updated_at' => '2024-09-26 13:21:51',
            ),
        ));
        
        
    }
}