<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DoctorSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('doctor_settings')->delete();
        
        \DB::table('doctor_settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'doctor_id' => 1,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'https://www.facebook.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            1 => 
            array (
                'id' => 2,
                'doctor_id' => 1,
                'name' => 'twitter/X_url',
                'display_name' => 'Twitter/X Url',
                'value' => 'https://twitter.com/',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-11 09:35:49',
                'updated_at' => '2024-07-11 09:35:49',
            ),
            2 => 
            array (
                'id' => 3,
                'doctor_id' => 1,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            3 => 
            array (
                'id' => 4,
                'doctor_id' => 1,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'Tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            4 => 
            array (
                'id' => 5,
                'doctor_id' => 1,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            5 => 
            array (
                'id' => 6,
                'doctor_id' => 1,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            6 => 
            array (
                'id' => 7,
                'doctor_id' => 1,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            7 => 
            array (
                'id' => 8,
                'doctor_id' => 1,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            8 => 
            array (
                'id' => 9,
                'doctor_id' => 1,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            9 => 
            array (
                'id' => 10,
                'doctor_id' => 64,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            10 => 
            array (
                'id' => 11,
                'doctor_id' => 64,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X Url',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            11 => 
            array (
                'id' => 12,
                'doctor_id' => 64,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            12 => 
            array (
                'id' => 13,
                'doctor_id' => 64,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'Tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            13 => 
            array (
                'id' => 14,
                'doctor_id' => 64,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'Linkedlin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            14 => 
            array (
                'id' => 15,
                'doctor_id' => 64,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'Whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            15 => 
            array (
                'id' => 16,
                'doctor_id' => 64,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'Snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            16 => 
            array (
                'id' => 17,
                'doctor_id' => 64,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            17 => 
            array (
                'id' => 18,
                'doctor_id' => 64,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'Pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:21:51',
                'updated_at' => '2024-07-24 18:21:51',
            ),
            18 => 
            array (
                'id' => 19,
                'doctor_id' => 65,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:38',
                'updated_at' => '2024-07-24 18:46:38',
            ),
            19 => 
            array (
                'id' => 20,
                'doctor_id' => 65,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            20 => 
            array (
                'id' => 21,
                'doctor_id' => 65,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            21 => 
            array (
                'id' => 22,
                'doctor_id' => 65,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            22 => 
            array (
                'id' => 23,
                'doctor_id' => 65,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkdlein.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            23 => 
            array (
                'id' => 24,
                'doctor_id' => 65,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            24 => 
            array (
                'id' => 25,
                'doctor_id' => 65,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            25 => 
            array (
                'id' => 26,
                'doctor_id' => 65,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            26 => 
            array (
                'id' => 27,
                'doctor_id' => 65,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:46:39',
                'updated_at' => '2024-07-24 18:46:39',
            ),
            27 => 
            array (
                'id' => 28,
                'doctor_id' => 62,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            28 => 
            array (
                'id' => 29,
                'doctor_id' => 62,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            29 => 
            array (
                'id' => 30,
                'doctor_id' => 62,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            30 => 
            array (
                'id' => 31,
                'doctor_id' => 62,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            31 => 
            array (
                'id' => 32,
                'doctor_id' => 62,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkdelin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            32 => 
            array (
                'id' => 33,
                'doctor_id' => 62,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            33 => 
            array (
                'id' => 34,
                'doctor_id' => 62,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            34 => 
            array (
                'id' => 35,
                'doctor_id' => 62,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            35 => 
            array (
                'id' => 36,
                'doctor_id' => 62,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:47:59',
                'updated_at' => '2024-07-24 18:47:59',
            ),
            36 => 
            array (
                'id' => 37,
                'doctor_id' => 66,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            37 => 
            array (
                'id' => 38,
                'doctor_id' => 66,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            38 => 
            array (
                'id' => 39,
                'doctor_id' => 66,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            39 => 
            array (
                'id' => 40,
                'doctor_id' => 66,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            40 => 
            array (
                'id' => 41,
                'doctor_id' => 66,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            41 => 
            array (
                'id' => 42,
                'doctor_id' => 66,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            42 => 
            array (
                'id' => 43,
                'doctor_id' => 66,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            43 => 
            array (
                'id' => 44,
                'doctor_id' => 66,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            44 => 
            array (
                'id' => 45,
                'doctor_id' => 66,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-24 18:52:37',
                'updated_at' => '2024-07-24 18:52:37',
            ),
            45 => 
            array (
                'id' => 46,
                'doctor_id' => 63,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'www.Fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            46 => 
            array (
                'id' => 47,
                'doctor_id' => 63,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X Url',
                'value' => 'www.twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            47 => 
            array (
                'id' => 48,
                'doctor_id' => 63,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'www.youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            48 => 
            array (
                'id' => 49,
                'doctor_id' => 63,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'www.tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            49 => 
            array (
                'id' => 50,
                'doctor_id' => 63,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'www.linkdein.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            50 => 
            array (
                'id' => 51,
                'doctor_id' => 63,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'www.whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            51 => 
            array (
                'id' => 52,
                'doctor_id' => 63,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'www.snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            52 => 
            array (
                'id' => 53,
                'doctor_id' => 63,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'www.instgram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            53 => 
            array (
                'id' => 54,
                'doctor_id' => 63,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'www.pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:47:59',
                'updated_at' => '2024-07-25 15:47:59',
            ),
            54 => 
            array (
                'id' => 55,
                'doctor_id' => 60,
                'name' => 'facebook_url',
                'display_name' => 'Facebook Url',
                'value' => 'facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            55 => 
            array (
                'id' => 56,
                'doctor_id' => 60,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X Url',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            56 => 
            array (
                'id' => 57,
                'doctor_id' => 60,
                'name' => 'youtube_url',
                'display_name' => 'Youtube Url',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            57 => 
            array (
                'id' => 58,
                'doctor_id' => 60,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok Url',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            58 => 
            array (
                'id' => 59,
                'doctor_id' => 60,
                'name' => 'linkedin_url',
                'display_name' => 'LinkedIn Url',
                'value' => 'linkedlin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            59 => 
            array (
                'id' => 60,
                'doctor_id' => 60,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp Url',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            60 => 
            array (
                'id' => 61,
                'doctor_id' => 60,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat Url',
                'value' => 'Snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            61 => 
            array (
                'id' => 62,
                'doctor_id' => 60,
                'name' => 'instagram_url',
                'display_name' => 'Instagram Url',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            62 => 
            array (
                'id' => 63,
                'doctor_id' => 60,
                'name' => 'pinterest_url',
                'display_name' => 'PinTerest Url',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-07-25 15:50:01',
                'updated_at' => '2024-07-25 15:50:01',
            ),
            63 => 
            array (
                'id' => 64,
                'doctor_id' => 77,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            64 => 
            array (
                'id' => 65,
                'doctor_id' => 77,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            65 => 
            array (
                'id' => 66,
                'doctor_id' => 77,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            66 => 
            array (
                'id' => 67,
                'doctor_id' => 77,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            67 => 
            array (
                'id' => 68,
                'doctor_id' => 77,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            68 => 
            array (
                'id' => 69,
                'doctor_id' => 77,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            69 => 
            array (
                'id' => 70,
                'doctor_id' => 77,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            70 => 
            array (
                'id' => 71,
                'doctor_id' => 77,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            71 => 
            array (
                'id' => 72,
                'doctor_id' => 77,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:34:02',
                'updated_at' => '2024-09-16 14:34:02',
            ),
            72 => 
            array (
                'id' => 73,
                'doctor_id' => 73,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            73 => 
            array (
                'id' => 74,
                'doctor_id' => 73,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            74 => 
            array (
                'id' => 75,
                'doctor_id' => 73,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            75 => 
            array (
                'id' => 76,
                'doctor_id' => 73,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            76 => 
            array (
                'id' => 77,
                'doctor_id' => 73,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            77 => 
            array (
                'id' => 78,
                'doctor_id' => 73,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'whatapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            78 => 
            array (
                'id' => 79,
                'doctor_id' => 73,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            79 => 
            array (
                'id' => 80,
                'doctor_id' => 73,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            80 => 
            array (
                'id' => 81,
                'doctor_id' => 73,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 14:37:36',
                'updated_at' => '2024-09-16 14:37:36',
            ),
            81 => 
            array (
                'id' => 82,
                'doctor_id' => 78,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            82 => 
            array (
                'id' => 83,
                'doctor_id' => 78,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            83 => 
            array (
                'id' => 84,
                'doctor_id' => 78,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            84 => 
            array (
                'id' => 85,
                'doctor_id' => 78,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            85 => 
            array (
                'id' => 86,
                'doctor_id' => 78,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            86 => 
            array (
                'id' => 87,
                'doctor_id' => 78,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            87 => 
            array (
                'id' => 88,
                'doctor_id' => 78,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            88 => 
            array (
                'id' => 89,
                'doctor_id' => 78,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            89 => 
            array (
                'id' => 90,
                'doctor_id' => 78,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:22:54',
                'updated_at' => '2024-09-16 16:22:54',
            ),
            90 => 
            array (
                'id' => 91,
                'doctor_id' => 79,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            91 => 
            array (
                'id' => 92,
                'doctor_id' => 79,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            92 => 
            array (
                'id' => 93,
                'doctor_id' => 79,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            93 => 
            array (
                'id' => 94,
                'doctor_id' => 79,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            94 => 
            array (
                'id' => 95,
                'doctor_id' => 79,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            95 => 
            array (
                'id' => 96,
                'doctor_id' => 79,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            96 => 
            array (
                'id' => 97,
                'doctor_id' => 79,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            97 => 
            array (
                'id' => 98,
                'doctor_id' => 79,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            98 => 
            array (
                'id' => 99,
                'doctor_id' => 79,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:28:30',
                'updated_at' => '2024-09-16 16:28:30',
            ),
            99 => 
            array (
                'id' => 100,
                'doctor_id' => 80,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:33:51',
                'updated_at' => '2024-09-16 16:33:51',
            ),
        ));
        \DB::table('doctor_settings')->insert(array (
            0 => 
            array (
                'id' => 101,
                'doctor_id' => 80,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:33:51',
                'updated_at' => '2024-09-16 16:33:51',
            ),
            1 => 
            array (
                'id' => 102,
                'doctor_id' => 80,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:33:51',
                'updated_at' => '2024-09-16 16:33:51',
            ),
            2 => 
            array (
                'id' => 103,
                'doctor_id' => 80,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'TikTok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:36:40',
                'updated_at' => '2024-09-16 17:36:40',
            ),
            3 => 
            array (
                'id' => 104,
                'doctor_id' => 80,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:36:40',
                'updated_at' => '2024-09-16 17:36:40',
            ),
            4 => 
            array (
                'id' => 105,
                'doctor_id' => 80,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'whatapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:36:40',
                'updated_at' => '2024-09-16 17:36:40',
            ),
            5 => 
            array (
                'id' => 106,
                'doctor_id' => 80,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:36:40',
                'updated_at' => '2024-09-16 17:36:40',
            ),
            6 => 
            array (
                'id' => 107,
                'doctor_id' => 80,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:36:40',
                'updated_at' => '2024-09-16 17:36:40',
            ),
            7 => 
            array (
                'id' => 108,
                'doctor_id' => 80,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:36:40',
                'updated_at' => '2024-09-16 17:36:40',
            ),
            8 => 
            array (
                'id' => 109,
                'doctor_id' => 81,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:39:44',
                'updated_at' => '2024-09-16 16:39:44',
            ),
            9 => 
            array (
                'id' => 110,
                'doctor_id' => 81,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'twittwer.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:39:44',
                'updated_at' => '2024-09-16 16:39:44',
            ),
            10 => 
            array (
                'id' => 111,
                'doctor_id' => 81,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 16:39:44',
                'updated_at' => '2024-09-16 16:39:44',
            ),
            11 => 
            array (
                'id' => 112,
                'doctor_id' => 81,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'Tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:35:17',
                'updated_at' => '2024-09-16 17:35:17',
            ),
            12 => 
            array (
                'id' => 113,
                'doctor_id' => 81,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:35:17',
                'updated_at' => '2024-09-16 17:35:17',
            ),
            13 => 
            array (
                'id' => 114,
                'doctor_id' => 81,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'whatapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:35:17',
                'updated_at' => '2024-09-16 17:35:17',
            ),
            14 => 
            array (
                'id' => 115,
                'doctor_id' => 81,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:35:17',
                'updated_at' => '2024-09-16 17:35:17',
            ),
            15 => 
            array (
                'id' => 116,
                'doctor_id' => 81,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:35:17',
                'updated_at' => '2024-09-16 17:35:17',
            ),
            16 => 
            array (
                'id' => 117,
                'doctor_id' => 81,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'Pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:35:17',
                'updated_at' => '2024-09-16 17:35:17',
            ),
            17 => 
            array (
                'id' => 118,
                'doctor_id' => 82,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Fackbook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            18 => 
            array (
                'id' => 119,
                'doctor_id' => 82,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            19 => 
            array (
                'id' => 120,
                'doctor_id' => 82,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            20 => 
            array (
                'id' => 121,
                'doctor_id' => 82,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'TikTok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            21 => 
            array (
                'id' => 122,
                'doctor_id' => 82,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'Linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            22 => 
            array (
                'id' => 123,
                'doctor_id' => 82,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'Whatapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            23 => 
            array (
                'id' => 124,
                'doctor_id' => 82,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            24 => 
            array (
                'id' => 125,
                'doctor_id' => 82,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            25 => 
            array (
                'id' => 126,
                'doctor_id' => 82,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:27:25',
                'updated_at' => '2024-09-16 17:27:25',
            ),
            26 => 
            array (
                'id' => 127,
                'doctor_id' => 76,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            27 => 
            array (
                'id' => 128,
                'doctor_id' => 76,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            28 => 
            array (
                'id' => 129,
                'doctor_id' => 76,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            29 => 
            array (
                'id' => 130,
                'doctor_id' => 76,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'Tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            30 => 
            array (
                'id' => 131,
                'doctor_id' => 76,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            31 => 
            array (
                'id' => 132,
                'doctor_id' => 76,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'Whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            32 => 
            array (
                'id' => 133,
                'doctor_id' => 76,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'Snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            33 => 
            array (
                'id' => 134,
                'doctor_id' => 76,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            34 => 
            array (
                'id' => 135,
                'doctor_id' => 76,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'Pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:38:44',
                'updated_at' => '2024-09-16 17:38:44',
            ),
            35 => 
            array (
                'id' => 136,
                'doctor_id' => 75,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            36 => 
            array (
                'id' => 137,
                'doctor_id' => 75,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            37 => 
            array (
                'id' => 138,
                'doctor_id' => 75,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            38 => 
            array (
                'id' => 139,
                'doctor_id' => 75,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'Tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            39 => 
            array (
                'id' => 140,
                'doctor_id' => 75,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            40 => 
            array (
                'id' => 141,
                'doctor_id' => 75,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'whatsapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            41 => 
            array (
                'id' => 142,
                'doctor_id' => 75,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            42 => 
            array (
                'id' => 143,
                'doctor_id' => 75,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            43 => 
            array (
                'id' => 144,
                'doctor_id' => 75,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'Pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:41:20',
                'updated_at' => '2024-09-16 17:41:20',
            ),
            44 => 
            array (
                'id' => 145,
                'doctor_id' => 74,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            45 => 
            array (
                'id' => 146,
                'doctor_id' => 74,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            46 => 
            array (
                'id' => 147,
                'doctor_id' => 74,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            47 => 
            array (
                'id' => 148,
                'doctor_id' => 74,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'TikTok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            48 => 
            array (
                'id' => 149,
                'doctor_id' => 74,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'LInkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            49 => 
            array (
                'id' => 150,
                'doctor_id' => 74,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'Whatapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            50 => 
            array (
                'id' => 151,
                'doctor_id' => 74,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'Snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            51 => 
            array (
                'id' => 152,
                'doctor_id' => 74,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            52 => 
            array (
                'id' => 153,
                'doctor_id' => 74,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'Pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:44:16',
                'updated_at' => '2024-09-16 17:44:16',
            ),
            53 => 
            array (
                'id' => 154,
                'doctor_id' => 72,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => 'Facebook.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            54 => 
            array (
                'id' => 155,
                'doctor_id' => 72,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            55 => 
            array (
                'id' => 156,
                'doctor_id' => 72,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => 'Youtube.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            56 => 
            array (
                'id' => 157,
                'doctor_id' => 72,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => 'Tiktok.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            57 => 
            array (
                'id' => 158,
                'doctor_id' => 72,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => 'Linkedin.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            58 => 
            array (
                'id' => 159,
                'doctor_id' => 72,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => 'Whatapp.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            59 => 
            array (
                'id' => 160,
                'doctor_id' => 72,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => 'Snapchat.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            60 => 
            array (
                'id' => 161,
                'doctor_id' => 72,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => 'Instagram.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            61 => 
            array (
                'id' => 162,
                'doctor_id' => 72,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => 'Pinterest.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:46:31',
                'updated_at' => '2024-09-16 17:46:31',
            ),
            62 => 
            array (
                'id' => 163,
                'doctor_id' => 1,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => 'Twitter.com',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-16 17:49:29',
                'updated_at' => '2024-09-16 17:49:29',
            ),
            63 => 
            array (
                'id' => 164,
                'doctor_id' => 83,
                'name' => 'calendly_link',
                'display_name' => 'Calendly Link',
                'value' => 'dwrdsgds',
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-26 12:58:54',
                'updated_at' => '2024-09-26 12:58:54',
            ),
            64 => 
            array (
                'id' => 165,
                'doctor_id' => 85,
                'name' => 'facebook_url',
                'display_name' => 'Facebook',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            65 => 
            array (
                'id' => 166,
                'doctor_id' => 85,
                'name' => 'twitter_url',
                'display_name' => 'Twitter/X',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            66 => 
            array (
                'id' => 167,
                'doctor_id' => 85,
                'name' => 'youtube_url',
                'display_name' => 'Youtube',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            67 => 
            array (
                'id' => 168,
                'doctor_id' => 85,
                'name' => 'tiktok_url',
                'display_name' => 'TikTok',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            68 => 
            array (
                'id' => 169,
                'doctor_id' => 85,
                'name' => 'linkedin_url',
                'display_name' => 'Linkedin',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            69 => 
            array (
                'id' => 170,
                'doctor_id' => 85,
                'name' => 'whatsapp_url',
                'display_name' => 'Whatsapp',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            70 => 
            array (
                'id' => 171,
                'doctor_id' => 85,
                'name' => 'snapchat_url',
                'display_name' => 'Snapchat',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            71 => 
            array (
                'id' => 172,
                'doctor_id' => 85,
                'name' => 'instagram_url',
                'display_name' => 'Instagram',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
            72 => 
            array (
                'id' => 173,
                'doctor_id' => 85,
                'name' => 'pinterest_url',
                'display_name' => 'Pinterest',
                'value' => NULL,
                'is_specific' => 0,
                'type' => NULL,
                'page' => NULL,
                'created_at' => '2024-09-27 18:13:14',
                'updated_at' => '2024-09-27 18:13:14',
            ),
        ));
        
        
    }
}