<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DoctorReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('doctor_reviews')->delete();
        
        \DB::table('doctor_reviews')->insert(array (
            0 => 
            array (
                'id' => 2,
                'doctor_id' => 25,
                'patient_id' => 50,
                'rating' => 3.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Their extensive knowledge and expertise were evident in every aspect of my treatment. They took the time to thoroughly explain my diagnosis and treatment options, answering all my questions with patience and clarity. I never felt rushed, and it was clear that Dr. [Doctor\'s Name] truly cares about their patients\' well-being.',
                'is_active' => 1,
                'is_approved' => 1,
                'is_featured' => 0,
                'created_at' => '2024-07-10 17:05:02',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'doctor_id' => 1,
                'patient_id' => 52,
                'rating' => 4.0,
                'experience' => 2.0,
                'communication' => 4.0,
                'service' => 3.0,
                'comment' => 'I had the pleasure of being treated by Dr. Sophia John, and I couldn’t have asked for a better experience. As an MBBS doctor, her medical knowledge is impressive, but what truly stood out to me was her warm and compassionate approach.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 14:46:02',
                'updated_at' => '2024-09-20 14:46:02',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'doctor_id' => 60,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 4.0,
                'communication' => 5.0,
                'service' => 4.0,
                'comment' => 'I recently had the opportunity to be treated by Dr. Alexander, and I am extremely satisfied with the care I received. As an MBBS doctor, he demonstrated a deep understanding of my condition.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 14:49:47',
                'updated_at' => '2024-09-20 14:49:47',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'doctor_id' => 62,
                'patient_id' => 52,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'I had a great experience with Dr. Miguel. he was very attentive and took the time to listen to all my concerns. The consultation didn\'t feel rushed, and she explained everything clearly.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:13:55',
                'updated_at' => '2024-09-20 15:13:55',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'doctor_id' => 63,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Dr. Amrik is amazing! I was nervous going in, but she made me feel comfortable right away. She is incredibly thorough and patient, explaining every detail of my diagnosis and treatment options.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:15:17',
                'updated_at' => '2024-09-20 15:15:17',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'doctor_id' => 64,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 4.0,
                'communication' => 5.0,
                'service' => 4.0,
                'comment' => 'Dr. Huges is a fantastic physician! He took the time to really understand my symptoms and made sure I felt comfortable throughout the entire visit',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:16:30',
                'updated_at' => '2024-09-20 15:16:30',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'doctor_id' => 65,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Dr. Morgan is exceptional! From the moment I walked in, I felt like I was in good hands. She was very attentive and empathetic',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:18:01',
                'updated_at' => '2024-09-20 15:18:01',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'doctor_id' => 66,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Dr. Emiliy is amazing! I was nervous going in, but she made me feel comfortable right away. She is incredibly thorough and patient, explaining every detail of my diagnosis and treatment options.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:20:44',
                'updated_at' => '2024-09-20 15:20:44',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'doctor_id' => 66,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Dr. Emiliy is amazing! I was nervous going in, but she made me feel comfortable right away. She is incredibly thorough and patient, explaining every detail of my diagnosis and treatment options.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:22:06',
                'updated_at' => '2024-09-20 15:22:06',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'doctor_id' => 66,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Dr. Emiliy is amazing! I was nervous going in, but she made me feel comfortable right away. She is incredibly thorough and patient, explaining every detail of my diagnosis and treatment options.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:22:42',
                'updated_at' => '2024-09-20 15:22:42',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'doctor_id' => 66,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Dr. Emiliy is amazing! I was nervous going in, but she made me feel comfortable right away. She is incredibly thorough and patient, explaining every detail of my diagnosis and treatment options.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:22:43',
                'updated_at' => '2024-09-20 15:22:43',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'doctor_id' => 72,
                'patient_id' => 52,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 3.0,
                'comment' => 'Dr. James is outstanding! He was not only professional but also very approachable. He took the time to answer all my questions,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:23:57',
                'updated_at' => '2024-09-20 15:23:57',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'doctor_id' => 73,
                'patient_id' => 52,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was incredibly knowledgeable and made me feel comfortable throughout the entire appointment',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:25:36',
                'updated_at' => '2024-09-20 15:25:36',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'doctor_id' => 74,
                'patient_id' => 52,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor provided excellent care, taking time to thoroughly assess my symptoms and explain the treatment options. They were patient and never made me feel rushed,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:27:09',
                'updated_at' => '2024-09-20 15:27:09',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'doctor_id' => 75,
                'patient_id' => 52,
                'rating' => 3.0,
                'experience' => 2.0,
                'communication' => 4.0,
                'service' => 3.0,
                'comment' => 'The doctor was attentive, professional, and very thorough. They really took the time to listen to my concerns and offered clear, helpful advice.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:28:17',
                'updated_at' => '2024-09-20 15:28:17',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 18,
                'doctor_id' => 76,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was excellent—very approachable and easy to talk to. They explained everything clearly and made sure I understood the diagnosis and treatment plan.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:29:04',
                'updated_at' => '2024-09-20 15:29:04',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 19,
                'doctor_id' => 77,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was excellent—very approachable and easy to talk to. They explained everything clearly and made sure I understood the diagnosis and treatment plan.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:29:42',
                'updated_at' => '2024-09-20 15:29:42',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 20,
                'doctor_id' => 78,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was attentive, professional, and very thorough. They really took the time to listen to my concerns and offered clear, helpful advice.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:30:18',
                'updated_at' => '2024-09-20 15:30:18',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 21,
                'doctor_id' => 79,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor provided excellent care, taking time to thoroughly assess my symptoms and explain the treatment options. They were patient and never made me feel rushed,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:30:39',
                'updated_at' => '2024-09-20 15:30:39',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 22,
                'doctor_id' => 80,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was incredibly knowledgeable and made me feel comfortable throughout the entire appointment',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:31:12',
                'updated_at' => '2024-09-20 15:31:12',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 23,
                'doctor_id' => 81,
                'patient_id' => 52,
                'rating' => 3.0,
                'experience' => 2.0,
                'communication' => 4.0,
                'service' => 5.0,
                'comment' => 'The doctor was attentive, professional, and very thorough. They really took the time to listen to my concerns and offered clear, helpful advice.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:31:32',
                'updated_at' => '2024-09-20 15:31:32',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 24,
                'doctor_id' => 82,
                'patient_id' => 52,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was excellent—very approachable and easy to talk to. They explained everything clearly and made sure I understood the diagnosis and treatment plan.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:31:55',
                'updated_at' => '2024-09-20 15:31:55',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 26,
                'doctor_id' => 1,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was very attentive and made me feel at ease from the moment I arrived. They took the time to ask detailed questions and really listened to my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:36:44',
                'updated_at' => '2024-09-20 15:36:44',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 27,
                'doctor_id' => 60,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was very attentive and made me feel at ease from the moment I arrived. They took the time to ask detailed questions and really listened to my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:37:26',
                'updated_at' => '2024-09-20 15:37:26',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 28,
                'doctor_id' => 62,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 3.0,
                'comment' => 'The doctor provided outstanding care and support during my visit. They took the time to listen to my concerns and answered all my questions patiently.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:38:06',
                'updated_at' => '2024-09-20 15:38:06',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 29,
                'doctor_id' => 63,
                'patient_id' => 50,
                'rating' => 3.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 3.0,
                'comment' => 'The doctor provided outstanding care and support during my visit. They took the time to listen to my concerns and answered all my questions patiently.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:38:33',
                'updated_at' => '2024-09-20 15:38:33',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 30,
                'doctor_id' => 64,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I appreciated how thorough the examination was, and the explanations were easy to follow. The office was comfortable and well-maintained,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:39:55',
                'updated_at' => '2024-09-20 15:39:55',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 31,
                'doctor_id' => 65,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was incredibly compassionate and attentive. They took the time to understand my symptoms and walked me through the entire process',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:40:51',
                'updated_at' => '2024-09-20 15:40:51',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 32,
                'doctor_id' => 72,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 5.0,
                'service' => 4.0,
                'comment' => 'I appreciated how thorough the examination was, and the explanations were easy to follow. The office was comfortable and well-maintained,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:42:45',
                'updated_at' => '2024-09-20 15:42:45',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 33,
                'doctor_id' => 72,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 5.0,
                'service' => 4.0,
                'comment' => 'I appreciated how thorough the examination was, and the explanations were easy to follow. The office was comfortable and well-maintained,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:42:46',
                'updated_at' => '2024-09-20 15:42:46',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 34,
                'doctor_id' => 73,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was very attentive and made me feel at ease from the moment I arrived. They took the time to ask detailed questions and really listened to my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:44:33',
                'updated_at' => '2024-09-20 15:44:33',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 35,
                'doctor_id' => 73,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was very attentive and made me feel at ease from the moment I arrived. They took the time to ask detailed questions and really listened to my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:44:34',
                'updated_at' => '2024-09-20 15:44:34',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 36,
                'doctor_id' => 74,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was incredibly compassionate and attentive. They took the time to understand my symptoms and walked me through the entire process',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:45:07',
                'updated_at' => '2024-09-20 15:45:07',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 37,
                'doctor_id' => 75,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was excellent—very approachable and easy to talk to. They explained everything clearly and made sure I understood the diagnosis and treatment plan.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:45:43',
                'updated_at' => '2024-09-20 15:45:43',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 38,
                'doctor_id' => 76,
                'patient_id' => 50,
                'rating' => 2.0,
                'experience' => 1.0,
                'communication' => 2.0,
                'service' => 2.0,
                'comment' => 'I appreciated how thorough the examination was, and the explanations were easy to follow. The office was comfortable and well-maintained,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:46:14',
                'updated_at' => '2024-09-20 15:46:14',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 39,
                'doctor_id' => 77,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was incredibly knowledgeable and made me feel comfortable throughout the entire appointment',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:46:40',
                'updated_at' => '2024-09-20 15:46:40',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 40,
                'doctor_id' => 78,
                'patient_id' => 50,
                'rating' => 3.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor provided outstanding care and support during my visit. They took the time to listen to my concerns and answered all my questions patiently.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:47:10',
                'updated_at' => '2024-09-20 15:47:10',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 41,
                'doctor_id' => 79,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was incredibly compassionate and attentive. They took the time to understand my symptoms and walked me through the entire process',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:47:30',
                'updated_at' => '2024-09-20 15:47:30',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 42,
                'doctor_id' => 80,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 3.0,
                'communication' => 1.0,
                'service' => 2.0,
                'comment' => 'I appreciated how thorough the examination was, and the explanations were easy to follow. The office was comfortable and well-maintained,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:47:49',
                'updated_at' => '2024-09-20 15:47:49',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 43,
                'doctor_id' => 81,
                'patient_id' => 50,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 5.0,
                'comment' => 'The doctor provided outstanding care and support during my visit. They took the time to listen to my concerns and answered all my questions patiently.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:48:05',
                'updated_at' => '2024-09-20 15:48:05',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 44,
                'doctor_id' => 82,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was incredibly compassionate and attentive. They took the time to understand my symptoms and walked me through the entire process',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:48:27',
                'updated_at' => '2024-09-20 15:48:27',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 45,
                'doctor_id' => 1,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was fantastic! They took the time to listen to my concerns and provided thoughtful, clear explanations. I felt completely at ease during the appointment',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:54:14',
                'updated_at' => '2024-09-20 15:54:14',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 46,
                'doctor_id' => 60,
                'patient_id' => 51,
                'rating' => 1.0,
                'experience' => 1.0,
                'communication' => 1.0,
                'service' => 1.0,
                'comment' => 'The doctor was remarkable! They made me feel comfortable and valued during my visit. Their attention to detail and willingness to answer all my questions really stood out.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:55:04',
                'updated_at' => '2024-09-20 15:55:04',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 47,
                'doctor_id' => 62,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 3.0,
                'service' => 3.0,
                'comment' => 'The doctor was excellent! They took the time to listen to my concerns and provided a thorough examination. I appreciated how they explained everything clearly',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:56:23',
                'updated_at' => '2024-09-20 15:56:23',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 48,
                'doctor_id' => 62,
                'patient_id' => 51,
                'rating' => 3.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 3.0,
                'comment' => 'The doctor was excellent! They took the time to listen to my concerns and provided a thorough examination. I appreciated how they explained everything clearly',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:57:03',
                'updated_at' => '2024-09-20 15:57:03',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 49,
                'doctor_id' => 63,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor provided outstanding care and support during my visit. They took the time to listen to my concerns and answered all my questions patiently.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:57:52',
                'updated_at' => '2024-09-20 15:57:52',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 50,
                'doctor_id' => 64,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was outstanding! They created a welcoming atmosphere and took the time to really listen to my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:58:37',
                'updated_at' => '2024-09-20 15:58:37',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 51,
                'doctor_id' => 65,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was fantastic! They took the time to listen to my concerns and provided thoughtful, clear explanations. I felt completely at ease during the appointment',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:59:25',
                'updated_at' => '2024-09-20 15:59:25',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 52,
                'doctor_id' => 66,
                'patient_id' => 51,
                'rating' => 3.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was incredibly compassionate and attentive. They took the time to understand my symptoms and walked me through the entire process',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 15:59:53',
                'updated_at' => '2024-09-20 15:59:53',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 53,
                'doctor_id' => 72,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 3.0,
                'comment' => 'The doctor was fantastic! They showed genuine concern for my well-being and took the time to answer all my questions.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:00:45',
                'updated_at' => '2024-09-20 16:00:45',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 54,
                'doctor_id' => 73,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was outstanding! They created a welcoming atmosphere and took the time to really listen to my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:01:13',
                'updated_at' => '2024-09-20 16:01:13',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 55,
                'doctor_id' => 74,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was exceptional! They were very attentive and took the time to thoroughly address my concerns',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:02:27',
                'updated_at' => '2024-09-20 16:02:27',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 56,
                'doctor_id' => 75,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor provided an excellent experience! They listened carefully to my concerns and took the time to explain everything in a way I could easily understand.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:03:02',
                'updated_at' => '2024-09-20 16:03:02',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 57,
                'doctor_id' => 76,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was fantastic! They were incredibly patient and took the time to understand my concerns. I appreciated their clear communication and the detailed explanations',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:03:42',
                'updated_at' => '2024-09-20 16:03:42',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 58,
                'doctor_id' => 77,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was wonderful! They made me feel comfortable right from the start and listened attentively to all my concerns.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:04:47',
                'updated_at' => '2024-09-20 16:04:47',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 59,
                'doctor_id' => 78,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was exceptional! They took the time to listen to my concerns and provided thoughtful, clear explanations.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:05:37',
                'updated_at' => '2024-09-20 16:05:37',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 60,
                'doctor_id' => 79,
                'patient_id' => 51,
                'rating' => 2.0,
                'experience' => 3.0,
                'communication' => 3.0,
                'service' => 3.0,
                'comment' => 'The doctor was fantastic! They were incredibly patient and took the time to understand my concerns. I appreciated their clear communication and the detailed explanations',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:06:13',
                'updated_at' => '2024-09-20 16:06:13',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 61,
                'doctor_id' => 80,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 3.0,
                'communication' => 4.0,
                'service' => 3.0,
                'comment' => 'The doctor was remarkable! They made me feel comfortable and valued during my visit. Their attention to detail and willingness to answer all my questions really stood out.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:07:47',
                'updated_at' => '2024-09-20 16:07:47',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 62,
                'doctor_id' => 81,
                'patient_id' => 51,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'The doctor was amazing! They were very attentive and took the time to address all my questions and concerns. I appreciated their thorough approach and how they explained',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:08:39',
                'updated_at' => '2024-09-20 16:08:39',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 63,
                'doctor_id' => 82,
                'patient_id' => 51,
                'rating' => 4.0,
                'experience' => 4.0,
                'communication' => 4.0,
                'service' => 4.0,
                'comment' => 'The doctor was excellent! They took the time to listen to my concerns and provided a thorough examination. I appreciated how they explained everything clearly',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-09-20 16:09:41',
                'updated_at' => '2024-09-20 16:09:41',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 64,
                'doctor_id' => 77,
                'patient_id' => 50,
                'rating' => 5.0,
                'experience' => 4.0,
                'communication' => 3.0,
                'service' => 5.0,
                'comment' => 'Hello world',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-10-01 16:19:42',
                'updated_at' => '2024-10-01 16:19:42',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}