<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DoctorCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('doctor_categories')->delete();
        
        \DB::table('doctor_categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '{"en":"Interventional Cardiology","hi":"हस्तक्षेपिक हृदय रोग विज्ञान","ar":"أمراض القلب التدخلية"}',
                'description' => '{"ar":null}',
                'slug' => 'interventional-cardiology-1',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 2,
                'created_at' => '2024-07-09 13:21:20',
                'updated_at' => '2024-07-25 16:08:37',
                'deleted_at' => '2024-07-25 16:08:37',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => '{"en":"Electrophysiology","hi":"विद्युत विज्ञान","ar":"الفيزيولوجيا الكهربية"}',
                'description' => '{"en":"<p>.</p>","hi":"<p>.</p>","ar":"<p>.</p>"}',
                'slug' => 'electrophysiology-2',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 2,
                'created_at' => '2024-07-09 13:22:25',
                'updated_at' => '2024-07-09 13:23:08',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => '{"en":"Clinical Neurophysiology","hi":"क्लिनिकल न्यूरोफिज़ियोलॉजी","ar":"الفسيولوجيا العصبية السريرية"}',
                'description' => '{"en":"<p>.</p>","hi":"<p>.</p>","ar":"<p>.</p>"}',
                'slug' => 'clinical-neurophysiology-3',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 3,
                'created_at' => '2024-07-09 13:26:47',
                'updated_at' => '2024-07-09 13:26:47',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '{"en":"Epileptology","hi":"मिर्गी विज्ञान","ar":"علم الصرع"}',
                'description' => '{"en":"<p>.</p>","hi":"<p>.</p>","ar":"<p>.</p>"}',
                'slug' => 'epileptology-4',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 3,
                'created_at' => '2024-07-09 13:31:01',
                'updated_at' => '2024-07-09 13:31:01',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '{"en":"Pediatric oncology","hi":"बाल रोग विज्ञान","ar":"طب الأورام السرطانية الأطفال"}',
                'description' => '{"en":"<p>.</p>","hi":"<p>.</p>","ar":"<p>.</p>"}',
                'slug' => 'pediatric-oncology-5',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 5,
                'created_at' => '2024-07-09 13:44:55',
                'updated_at' => '2024-07-25 17:17:31',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '{"en":"Hand Surgery","hi":"हाथ की सर्जरी","ar":"جراحة اليد"}',
                'description' => '{"ar":null}',
                'slug' => 'hand-surgery-6',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 4,
                'created_at' => '2024-07-09 13:46:46',
                'updated_at' => '2024-07-25 16:18:02',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '{"en":"Pediatric pulmonology","hi":"शिशु फेफड़ों का विज्ञान","ar":"طب الأمراض الرئوية الأطفال"}',
                'description' => '{"ar":null}',
                'slug' => 'pediatric-pulmonology-7',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 5,
                'created_at' => '2024-07-24 17:05:13',
                'updated_at' => '2024-07-25 17:18:31',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => '{"en":"General Orthopedics","hi":"सामान्य ऑर्थोपेडिक्स","ar":"الجراحة العظمية العامة"}',
                'description' => '{"en":"<p>dd</p>","ar":null}',
                'slug' => 'general-orthopedics-8',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 4,
                'created_at' => '2024-07-24 17:31:26',
                'updated_at' => '2024-07-25 16:16:45',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => '{"en":"Neuroimmunology","hi":"स्नायुआवरोधनशास्त्र","ar":"علم المناعة العصبية"}',
                'description' => '{"ar":null}',
                'slug' => 'neuroimmunology-9',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 3,
                'created_at' => '2024-07-24 17:31:48',
                'updated_at' => '2024-07-25 16:14:22',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => '{"en":"Neurophysiology","hi":"स्नायुवैज्ञानिकता","ar":"علم وظائف الأعصاب"}',
                'description' => '{"ar":null}',
                'slug' => 'neurophysiology-10',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 3,
                'created_at' => '2024-07-24 17:32:06',
                'updated_at' => '2024-07-25 16:13:15',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => '{"en":"Nuclear Cardiology","hi":"परमाणु हृदय रोग विज्ञान","ar":"الطب النووي للقلب"}',
            'description' => '{"en":"<p>Nuclear Cardiology is a specialized field of cardiology that uses radioactive substances (radiopharmaceuticals) and imaging techniques to diagnose and assess heart conditions. It includes procedures like myocardial perfusion imaging (MPI) and cardiac positron emission tomography (PET) scans to evaluate blood flow to the heart muscle, detect areas of damage, and assess overall heart function.</p>","hi":"<p>परमाणु हृदय रोग विज्ञान एक विशेषता हृदय रोग विज्ञान की शाखा है जो विकिरणीय द्रव्य (रेडियोफार्मास्युटिकल्स) और छवि प्रक्रियाओं का उपयोग करती है ताकि हृदय की स्थितियों का निदान और मूल्यांकन किया जा सके। इसमें मायोकार्डियल परफ्यूजन इमेजिंग (एमपीआई) और कार्डियक पॉजिट्रॉन इमिशन टोमोग्राफी (पीईटी) स्कैन्स जैसी प्रक्रियाएं शामिल होती हैं जो हृदय मांसपेशी को रक्त प्रवाह की मापदंडीकरण करने, क्षति के क्षेत्रों की पहचान करने और समग्र हृदय कार्यक्षमता का मूल्यांकन करने के लिए क</p>","ar":"<p>Nuclear Cardiology is a specialized field of cardiology that uses radioactive substances (radiopharmaceuticals) and imaging techniques to diagnose and assess heart conditions. It includes procedures like myocardial perfusion imaging (MPI) and cardiac positron emission tomography (PET) scans to evaluate blood flow to the heart muscle, detect areas of damage, and assess overall heart function.</p>"}',
                'slug' => 'nuclear-cardiology-11',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 2,
                'created_at' => '2024-07-24 17:32:32',
                'updated_at' => '2024-08-28 15:24:26',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => '{"en":"Interventional Cardiology","hi":"अन्तर्वेषणीय हृदय रोग विज्ञान","ar":"طب القلب التدخلي"}',
                'description' => '{"en":"<p>Interventional Cardiology is a branch of cardiology that uses catheter-based techniques to diagnose and treat cardiovascular diseases. It involves procedures such as angioplasty, stenting, and transcatheter valve interventions to restore blood flow and repair heart defects without the need for surgery.</p>","hi":"<p>अन्तर्वेषणीय हृदय रोग विज्ञान एक ऐसी हृदय रोग विज्ञान की शाखा है जो कैथेटर आधारित तकनीकों का उपयोग करती है ताकि हृदय रोगों का निदान और उपचार किया जा सके। इसमें एंजियोप्लास्टी, स्टेंटिंग, और ट्रांसकैथेटर वाल्व इंटरवेंशन जैसी प्रक्रियाएं शामिल होती हैं जिनके द्वारा रक्त प्रवाह को बहाल किया जाता है और हृदय के दोषों को सुधारा जाता है बिना सर्जरी की आवश्यकता के।</p>","ar":"<p>&nbsp;طب القلب التدخلي هو فرع من فروع طب القلب يستخدم تقنيات القسطرة لتشخيص وعلاج الأمراض القلبية والوعائية. يشمل الإجراءات مثل التمدد الركيزي، الأسيتنت، والتدخلات الصمامية عبر القسطرة لاستعادة تدفق الدم وإصلاح عيوب القلب دون الحاجة إلى جراحة.</p>"}',
                'slug' => 'interventional-cardiology-12',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 2,
                'created_at' => '2024-07-24 17:58:32',
                'updated_at' => '2024-07-25 16:08:06',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => '{"en":"Andrology","hi":"पुरुष विज्ञान","ar":"علم الذكورة"}',
                'description' => '{"ar":null}',
                'slug' => 'andrology-13',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 12,
                'created_at' => '2024-07-25 17:19:50',
                'updated_at' => '2024-09-11 15:22:51',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => '{"en":"Female Urology","hi":"महिला मूत्र विज्ञान","ar":"طب المسالك البولية للنساء"}',
                'description' => '{"ar":null}',
                'slug' => 'female-urology-14',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 6,
                'created_at' => '2024-07-25 17:21:06',
                'updated_at' => '2024-08-28 15:20:28',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => '{"en":"Neurogastroenterology","hi":"तंतुरेज़िक्त्र भोजनातन्त्रविज्ञान","ar":"علم الأمراض العصبية الهضمية"}',
                'description' => '{"ar":null}',
                'slug' => 'neurogastroenterology-15',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 7,
                'created_at' => '2024-07-25 17:22:47',
                'updated_at' => '2024-08-28 15:26:15',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => '{"en":"Hepatology","hi":"यकृत विज्ञान","ar":"طب الكبد"}',
                'description' => '{"ar":null}',
                'slug' => 'hepatology-16',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 7,
                'created_at' => '2024-07-25 17:23:25',
                'updated_at' => '2024-08-28 15:27:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => '{"en":"Forensic Psychiatry","hi":"न्यायिक मनोचिकित्सा","ar":"الطب النفسي الشرعي"}',
                'description' => '{"ar":null}',
                'slug' => 'forensic-psychiatry-17',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 8,
                'created_at' => '2024-07-25 17:24:51',
                'updated_at' => '2024-08-28 15:20:36',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => '{"en":"Geriatric Psychiatry","hi":"जेरिएट्रिक मानसिक रोग विज्ञान","ar":"الطب النفسي للمسنين"}',
                'description' => '{"ar":null}',
                'slug' => 'geriatric-psychiatry-18',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 8,
                'created_at' => '2024-07-25 17:26:23',
                'updated_at' => '2024-08-28 15:21:50',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => '{"en":"Corneal Surgery","hi":"कोर्नियल सर्जरी","ar":"جراحة القرنية"}',
                'description' => '{"ar":null}',
                'slug' => 'corneal-surgery-19',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 13,
                'created_at' => '2024-07-25 17:28:16',
                'updated_at' => '2024-09-11 15:25:34',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => '{"en":"Retinal Surgery","hi":"नेत्रपट सर्जरी","ar":"جراحة الشبكية"}',
                'description' => '{"ar":null}',
                'slug' => 'retinal-surgery-20',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 9,
                'created_at' => '2024-07-25 17:28:59',
                'updated_at' => '2024-08-28 15:24:49',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => '{"en":"Hematology","hi":"रक्त विज्ञान","ar":"علم الدم"}',
                'description' => '{"ar":null}',
                'slug' => 'hematology-21',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 10,
                'created_at' => '2024-07-25 17:30:19',
                'updated_at' => '2024-08-28 15:22:45',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => '{"en":"Nephrology","hi":"नेफ़्रोलॉजी","ar":"طب الكلى"}',
                'description' => '{"ar":null}',
                'slug' => 'nephrology-22',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 10,
                'created_at' => '2024-07-25 17:30:48',
                'updated_at' => '2024-08-28 15:26:43',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => '{"en":"Urogynecology","hi":"मूत्र-महिला रोग विज्ञान","ar":"التناسلية والبولية للنساء"}',
                'description' => '{"ar":null}',
                'slug' => 'urogynecology-23',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 11,
                'created_at' => '2024-07-25 17:32:39',
                'updated_at' => '2024-08-28 15:24:36',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => '{"en":"Adolescent Gynecology","hi":"किशोर महिला रोग विज्ञान","ar":"طب النساء للمراهقات"}',
                'description' => '{"ar":null}',
                'slug' => 'adolescent-gynecology-24',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 11,
                'created_at' => '2024-07-25 17:33:33',
                'updated_at' => '2024-08-28 15:19:24',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => '{"en":"Surgical Hospitalists","hi":"औद्योगिक डिज़ाइन","ar":"التصميم الصناعي"}',
                'description' => '{"ar":null}',
                'slug' => 'surgical-hospitalists-25',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 16,
                'created_at' => '2024-09-16 15:56:54',
                'updated_at' => '2024-09-16 15:57:10',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => '{"en":"Pediatric Hospitalists:","hi":"औद्योगिक डिज़ाइन","ar":"التصميم الصناعي"}',
                'description' => '{"ar":null}',
                'slug' => 'pediatric-hospitalists-26',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 16,
                'created_at' => '2024-09-16 15:57:52',
                'updated_at' => '2024-09-16 15:57:52',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => '{"en":"General Nephrologists","hi":"औद्योगिक डिज़ाइन","ar":"التصميم الصناعي"}',
                'description' => '{"ar":null}',
                'slug' => 'general-nephrologists-27',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 14,
                'created_at' => '2024-09-16 15:58:51',
                'updated_at' => '2024-09-16 15:58:51',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => '{"en":"Dialysis Nephrologists","hi":"औद्योगिक डिज़ाइन","ar":"التصميم الصناعي"}',
                'description' => '{"ar":null}',
                'slug' => 'dialysis-nephrologists-28',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 14,
                'created_at' => '2024-09-16 15:59:23',
                'updated_at' => '2024-09-16 15:59:23',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => '{"en":"Gynecologic Oncologists","hi":"औद्योगिक डिज़ाइन","ar":"التصميم الصناعي"}',
                'description' => '{"ar":null}',
                'slug' => 'gynecologic-oncologists-29',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 15,
                'created_at' => '2024-09-16 16:00:16',
                'updated_at' => '2024-09-16 16:00:16',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => '{"en":"Reproductive Endocrinologists","hi":"औद्योगिक डिज़ाइन","ar":"التصميم الصناعي"}',
                'description' => '{"ar":null}',
                'slug' => 'reproductive-endocrinologists-30',
                'is_active' => 1,
                'is_featured' => 0,
                'icon' => NULL,
                'image' => NULL,
                'parent_category_id' => 15,
                'created_at' => '2024-09-16 16:00:41',
                'updated_at' => '2024-09-16 16:00:41',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}