<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PatientsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('patients')->delete();
        
        \DB::table('patients')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 2,
                'user_name' => 'jack',
                'country_id' => 167,
                'state_id' => 3176,
                'city_id' => 85437,
                'first_name' => 'Mary',
                'last_name' => 'Jennifer',
                'father_name' => NULL,
                'description' => 'Jack Testing Patient',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => 'D Ground People Colony',
                'address_line_2' => 'Faisalabad',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/652fcc3d5fab9.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-01 16:54:49',
                'updated_at' => '2024-04-01 13:46:54',
                'deleted_at' => '2024-04-01 13:46:54',
            ),
            1 => 
            array (
                'id' => 3,
                'user_id' => 18,
                'user_name' => 'James_Daniel',
                'country_id' => 19,
                'state_id' => 766,
                'city_id' => 8541,
                'first_name' => 'James',
                'last_name' => 'Daniel',
                'father_name' => NULL,
                'description' => 'asd asds',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => '123 Main Street
Anytown, USA
12345',
                'address_line_2' => '123 Main Street
Anytown, USA
12345',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/652fcb5adc5a7.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-09 09:16:12',
                'updated_at' => '2024-04-01 13:42:25',
                'deleted_at' => '2024-04-01 13:42:25',
            ),
            2 => 
            array (
                'id' => 25,
                'user_id' => 65,
                'user_name' => 'Oliver_Sarith',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Oliver',
                'last_name' => 'Sarith',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => '2345654',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/patients/66ebde9116412.png',
                'cover_image' => NULL,
                'created_at' => '2023-12-07 18:04:05',
                'updated_at' => '2024-09-19 13:19:29',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 50,
                'user_id' => 113,
                'user_name' => 'patient',
                'country_id' => 167,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'James',
                'last_name' => 'lee',
                'father_name' => 'asdasd',
                'description' => 'asasasa',
                'dob' => '2024-10-01',
                'gender' => NULL,
                'blood_group' => 'A-',
                'address_line_1' => '123123',
                'address_line_2' => '123123123',
                'zip_code' => '23',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/patients/66fd1dba82b9f.png',
                'cover_image' => NULL,
                'created_at' => '2024-07-08 12:30:31',
                'updated_at' => '2024-10-07 18:46:16',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 51,
                'user_id' => 136,
                'user_name' => 'harry1111',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Jenny',
                'last_name' => 'Lily',
                'father_name' => NULL,
                'description' => 'Harry Potter Description',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/patients/66ab6b3ae0530.png',
                'cover_image' => NULL,
                'created_at' => '2024-08-01 16:02:18',
                'updated_at' => '2024-09-26 18:47:14',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 52,
                'user_id' => 3,
                'user_name' => '456',
                'country_id' => 16,
                'state_id' => NULL,
                'city_id' => 1963,
                'first_name' => 'Olivia',
                'last_name' => 'John',
                'father_name' => 'John',
                'description' => 'Dr. Sophia Williams is a renowned physician known for her unwavering dedication to patient care and her expertise in family medicine. With over a decade of experience, Dr. Williams has become a trusted healthcare provider in her community. She is highly regarded for her ability to connect with patients, offering them personalized care that addresses their unique needs.

Dr. Williams is passionate about preventive medicine and believes in empowering her patients through education. She regularly conducts health workshops and is actively involved in community health programs. Her commitment to staying updated with the latest medical advancements ensures that her patients receive the best possible care.',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => 'B+',
                'address_line_1' => 'line 1',
                'address_line_2' => 'line 2',
                'zip_code' => '5532320',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66ed418c4380d.png',
                'cover_image' => NULL,
                'created_at' => '2024-09-03 16:00:17',
                'updated_at' => '2024-10-07 18:12:41',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 53,
                'user_id' => 152,
                'user_name' => 'hetayor645',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'heta',
                'last_name' => 'yor',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-09-19 15:58:41',
                'updated_at' => '2024-09-19 15:58:41',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 54,
                'user_id' => 153,
                'user_name' => 'sdsdfsd',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'John',
                'last_name' => 'Daniel',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => 'sfasfsd',
                'address_line_2' => 'fsdfasf',
                'zip_code' => '65812',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66f3c08a8d83d.png',
                'cover_image' => NULL,
                'created_at' => '2024-09-25 12:43:18',
                'updated_at' => '2024-09-25 12:56:03',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 55,
                'user_id' => 154,
                'user_name' => 'jofragmailcom',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'jofra',
                'last_name' => 'lee',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => 'dsdsd',
                'address_line_2' => 'gsdgsdf',
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'icon' => NULL,
                'image' => '/images/profile_images/66f3c28da3f8f.png',
                'cover_image' => NULL,
                'created_at' => '2024-09-25 12:57:22',
                'updated_at' => '2024-09-27 11:34:09',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 56,
                'user_id' => 155,
                'user_name' => 'superadmingmailcom',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Jacque',
                'last_name' => 'james',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => 'asf',
                'address_line_2' => 'dsfsdf',
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66f3c3e9a1a1a.png',
                'cover_image' => NULL,
                'created_at' => '2024-09-25 13:02:57',
                'updated_at' => '2024-09-25 13:03:53',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 57,
                'user_id' => 156,
                'user_name' => 'trye',
                'country_id' => 167,
                'state_id' => 3175,
                'city_id' => 85361,
                'first_name' => 'ssdgsfdg',
                'last_name' => 'efdwhsdf',
                'father_name' => 'dsagas',
                'description' => 'sdfsdasdfsd',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => 'b+',
                'address_line_1' => 'wrgsdg',
                'address_line_2' => 'dgdgedsg',
                'zip_code' => '4741023',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66f4fdb47700a.png',
                'cover_image' => NULL,
                'created_at' => '2024-09-26 11:11:09',
                'updated_at' => '2024-09-26 11:22:59',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 58,
                'user_id' => 158,
                'user_name' => 'patienthealth',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Patient',
                'last_name' => 'Health',
                'father_name' => 'Health Consultant',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => 'A+',
                'address_line_1' => '1234 Elm Street, Apt 5B, Faketown, NY 12345, USA',
                'address_line_2' => '1234 Elm Street, Apt 5B, Faketown, NY 12345, USA',
                'zip_code' => '38210',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66f501ae6345a.png',
                'cover_image' => NULL,
                'created_at' => '2024-09-26 11:34:21',
                'updated_at' => '2024-09-26 11:39:42',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 59,
                'user_id' => 160,
                'user_name' => 'bilal',
                'country_id' => 167,
                'state_id' => 3176,
                'city_id' => 85437,
                'first_name' => 'Bilal',
                'last_name' => 'Naeem',
                'father_name' => 'Naeem',
                'description' => 'I am Bilal From Faisalabad',
                'dob' => '2024-09-27',
                'gender' => 'Male',
                'blood_group' => 'AB+',
                'address_line_1' => 'koh e noor',
                'address_line_2' => 'koh e noor',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66f68c2729b3f.png',
                'cover_image' => NULL,
                'created_at' => '2024-09-27 15:02:28',
                'updated_at' => '2024-10-03 18:25:59',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 60,
                'user_id' => 161,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Bilal',
                'last_name' => 'Naeem',
                'father_name' => NULL,
                'description' => '',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => 'sdf',
                'address_line_2' => 'sadf',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-09-27 19:23:19',
                'updated_at' => '2024-10-07 18:46:59',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 61,
                'user_id' => 163,
                'user_name' => 'bilalinvictus',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'M Bilal',
                'last_name' => 'Naeem',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-01 15:04:26',
                'updated_at' => '2024-10-01 15:10:20',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 62,
                'user_id' => 164,
                'user_name' => 'faizanfazal',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'faizan',
                'last_name' => 'fazal',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-03 15:52:11',
                'updated_at' => '2024-10-03 15:52:11',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 63,
                'user_id' => 165,
                'user_name' => 'capyfoxa',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Ria',
                'last_name' => 'Morris',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-03 18:02:55',
                'updated_at' => '2024-10-03 18:02:55',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 64,
                'user_id' => 167,
                'user_name' => 'bilaltest2',
                'country_id' => 167,
                'state_id' => 3176,
                'city_id' => 85437,
                'first_name' => 'bilal',
                'last_name' => 'naeem',
                'father_name' => 'naeem',
                'description' => 'test',
                'dob' => '2024-10-04',
                'gender' => 'male',
                'blood_group' => 'ab+',
                'address_line_1' => 'adr1',
                'address_line_2' => 'adr2',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-05 20:57:55',
                'updated_at' => '2024-10-05 21:39:02',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 65,
                'user_id' => 168,
                'user_name' => 'rojedyr',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Casey',
                'last_name' => 'Gamble',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-07 12:06:49',
                'updated_at' => '2024-10-07 12:06:49',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 66,
                'user_id' => 169,
                'user_name' => NULL,
                'country_id' => 112,
                'state_id' => 144,
                'city_id' => 65710,
                'first_name' => 'Ad consequatur Mini',
                'last_name' => 'Ab iusto doloremque',
                'father_name' => NULL,
                'description' => 'nbmb',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => 'Deserunt suscipit cu',
                'address_line_2' => 'Ea omnis culpa aliq',
                'zip_code' => '1231',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-07 13:09:38',
                'updated_at' => '2024-10-07 13:09:42',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 67,
                'user_id' => 170,
                'user_name' => 'asdasd',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Educational',
                'last_name' => 'Advisor',
                'father_name' => '34534',
                'description' => 'edfdsafs',
                'dob' => '2024-10-11',
                'gender' => 'male',
                'blood_group' => 'a+',
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/6703d94bd9414.png',
                'cover_image' => NULL,
                'created_at' => '2024-10-07 17:33:39',
                'updated_at' => '2024-10-07 17:51:49',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 68,
                'user_id' => 171,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'doctor1',
                'last_name' => 'asda',
                'father_name' => NULL,
                'description' => 'qwasdasasdasdaasddfsdafsadfasdasdas',
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => 'sdafsda',
                'address_line_2' => 'rwqerweqasd',
                'zip_code' => '12334',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-07 17:55:03',
                'updated_at' => '2024-10-07 17:55:03',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 69,
                'user_id' => 172,
                'user_name' => 'dikimahy',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'May',
                'last_name' => 'Cooley',
                'father_name' => NULL,
                'description' => NULL,
                'dob' => NULL,
                'gender' => NULL,
                'blood_group' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-10-07 17:55:52',
                'updated_at' => '2024-10-07 17:55:52',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}