<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PricingPlansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pricing_plans')->delete();
        
        \DB::table('pricing_plans')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Micky Mouse',
                'description' => '<p>Bronze some information</p>',
                'type' => 'doctor',
                'tagline' => 'Test Tagline For Micky Mouse',
                'image' => '/images/subscriptions/1673035867Screenshot from 2022-12-11 00-50-51.png',
                'color' => '#bc9494',
                'stripe_plan' => NULL,
                'price' => 0.0,
                'slug' => 'micky-mouse-1',
                'sort_order' => NULL,
                'is_active' => 0,
                'is_default' => 1,
                'is_paid' => 0,
                'created_at' => '2023-01-06 20:11:07',
                'updated_at' => '2023-10-04 16:49:15',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Basic',
                'description' => '<p>Basic</p>',
                'type' => 'clinic',
                'tagline' => NULL,
                'image' => NULL,
                'color' => '#000000',
                'stripe_plan' => NULL,
                'price' => 0.0,
                'slug' => 'basic-2',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 1,
                'is_paid' => 0,
                'created_at' => '2023-02-13 15:40:24',
                'updated_at' => '2023-03-15 22:23:04',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 49,
                'name' => 'Silver',
                'description' => '<p>silver</p>',
                'type' => 'doctor',
                'tagline' => NULL,
                'image' => NULL,
                'color' => '#000000',
                'stripe_plan' => NULL,
                'price' => 5.0,
                'slug' => 'silver-49',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 1,
                'is_paid' => 0,
                'created_at' => '2023-02-13 16:42:20',
                'updated_at' => '2024-05-11 17:15:06',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 50,
                'name' => 'Gold',
                'description' => '<p>gold</p>',
                'type' => 'doctor',
                'tagline' => NULL,
                'image' => '/images/subscriptions/63efba60307d7.png',
                'color' => '#000000',
                'stripe_plan' => NULL,
                'price' => 8.0,
                'slug' => 'gold-50',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 0,
                'created_at' => '2023-02-17 17:19:17',
                'updated_at' => '2024-05-11 17:15:22',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 51,
                'name' => 'Platinum',
                'description' => '<p>platinum</p>',
                'type' => 'doctor',
                'tagline' => NULL,
                'image' => '/images/subscriptions/63efba60307d7.png',
                'color' => '#000000',
                'stripe_plan' => NULL,
                'price' => 10.0,
                'slug' => 'platinum-51',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 0,
                'created_at' => '2023-02-17 17:19:17',
                'updated_at' => '2024-05-11 17:19:52',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 52,
                'name' => 'silver',
                'description' => 'ok',
                'type' => NULL,
                'tagline' => NULL,
                'image' => NULL,
                'color' => NULL,
                'stripe_plan' => 'price_1MkY0VHTAHWwyrB6Vl3f8ZIT',
                'price' => 50.0,
                'slug' => 'silver-52',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 1,
                'created_at' => '2023-03-13 21:15:11',
                'updated_at' => '2023-11-17 19:37:21',
                'deleted_at' => '2023-11-17 19:37:21',
            ),
            6 => 
            array (
                'id' => 53,
                'name' => 'gold',
                'description' => 'Ok',
                'type' => 'doctor',
                'tagline' => NULL,
                'image' => NULL,
                'color' => '#000000',
                'stripe_plan' => 'price_1MkPGfHTAHWwyrB6thyCbJXk',
                'price' => 50.0,
                'slug' => 'diamond-53',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 1,
                'created_at' => '2023-03-13 21:15:11',
                'updated_at' => '2024-06-06 17:37:10',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 54,
                'name' => 'Platinum',
                'description' => 'Platinum Membership',
                'type' => NULL,
                'tagline' => NULL,
                'image' => NULL,
                'color' => NULL,
                'stripe_plan' => 'price_1MtCVpHTAHWwyrB6y9w1pYFi',
                'price' => 99.99,
                'slug' => 'platinum-54',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 1,
                'created_at' => '2023-09-12 19:53:23',
                'updated_at' => '2023-09-12 19:53:24',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 55,
                'name' => 'Platinium',
                'description' => '<p>ok</p>',
                'type' => 'doctor',
                'tagline' => NULL,
                'image' => NULL,
                'color' => '#000000',
                'stripe_plan' => NULL,
                'price' => 100.0,
                'slug' => 'platinium-55',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 0,
                'created_at' => '2023-11-14 15:32:37',
                'updated_at' => '2023-11-14 15:35:35',
                'deleted_at' => '2023-11-14 15:35:35',
            ),
            9 => 
            array (
                'id' => 56,
                'name' => 'Crown',
                'description' => '<p>ok</p>',
                'type' => 'doctor',
                'tagline' => NULL,
                'image' => NULL,
                'color' => '#000000',
                'stripe_plan' => NULL,
                'price' => 100.0,
                'slug' => 'crown-56',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 0,
                'created_at' => '2023-11-14 15:48:01',
                'updated_at' => '2023-11-14 15:49:12',
                'deleted_at' => '2023-11-14 15:49:12',
            ),
            10 => 
            array (
                'id' => 57,
                'name' => 'Titanium',
                'description' => 'some description belong to titanium plan',
                'type' => NULL,
                'tagline' => NULL,
                'image' => NULL,
                'color' => NULL,
                'stripe_plan' => 'price_1P5sKuHTAHWwyrB6eQNhfVxk',
                'price' => 1000.0,
                'slug' => 'titanium-57',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 1,
                'created_at' => '2024-06-06 17:37:10',
                'updated_at' => '2024-06-06 17:37:10',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 58,
                'name' => 'silver',
                'description' => 'ok',
                'type' => NULL,
                'tagline' => NULL,
                'image' => NULL,
                'color' => NULL,
                'stripe_plan' => 'price_1MkY0VHTAHWwyrB6Vl3f8ZIT',
                'price' => 50.0,
                'slug' => 'silver-58',
                'sort_order' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'is_paid' => 1,
                'created_at' => '2024-06-06 17:37:10',
                'updated_at' => '2024-06-06 17:37:10',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 59,
                'name' => 'asdfasd',
                'description' => '<p>asddasfsd</p>',
                'type' => 'doctor',
                'tagline' => 'sasd',
                'image' => NULL,
                'color' => '#000000',
                'stripe_plan' => NULL,
                'price' => 324.0,
                'slug' => 'asdfasd-59',
                'sort_order' => NULL,
                'is_active' => 0,
                'is_default' => 0,
                'is_paid' => 0,
                'created_at' => '2024-06-11 15:10:07',
                'updated_at' => '2024-06-11 15:10:17',
                'deleted_at' => '2024-06-11 15:10:17',
            ),
        ));
        
        
    }
}