<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('services')->delete();
        
        \DB::table('services')->insert(array (
            0 => 
            array (
                'id' => 1,
                'doctor_id' => NULL,
                'clinic_id' => NULL,
                'service_category_id' => 3,
                'name' => '{"en":"HydraFacial","hi":"dawfrawdaw","ar":"afawfaw"}',
                'description' => '{"en":"<p>You can book an appointment online through our website, via our mobile app, or by calling our office.</p>","hi":"<p>fafawf</p>","ar":"<p>fafawfawfaw</p>"}',
                'slug' => 'hydrafacial-1',
                'is_active' => 1,
                'is_approved' => 0,
                'approved_at' => NULL,
                'is_featured' => 0,
                'image' => '/images/services/66a0fc0a170f3.png',
                'video' => NULL,
                'price' => NULL,
                'created_at' => '2024-07-24 18:05:14',
                'updated_at' => '2024-10-02 14:44:23',
                'deleted_at' => '2024-10-02 14:44:23',
            ),
            1 => 
            array (
                'id' => 2,
                'doctor_id' => 1,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"Chronic Disease Management","hi":"पुरानी बीमारी प्रबंधन","ar":"إدارة الأمراض المزمنة"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ"}',
                'slug' => 'chronic-disease-management-2',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-07-27 12:27:47',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66a4a173e02f1.png',
                'video' => NULL,
                'price' => 20.0,
                'created_at' => '2024-07-27 12:27:47',
                'updated_at' => '2024-09-19 14:52:51',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'doctor_id' => 1,
                'clinic_id' => NULL,
                'service_category_id' => 3,
                'name' => '{"en":"Wellness Programs","hi":"वेलनेस प्रोग्राम","ar":"برامج العافية"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'slug' => 'wellness-programs-3',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-07-27 13:22:54',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66a4ae5e1801c.png',
                'video' => NULL,
                'price' => 30.0,
                'created_at' => '2024-07-27 13:22:54',
                'updated_at' => '2024-09-19 14:51:27',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'doctor_id' => 1,
                'clinic_id' => NULL,
                'service_category_id' => 2,
                'name' => '{"en":"Blood Pressure Screening","hi":"रक्तचाप जांच","ar":"فحص ضغط الدم"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ"}',
                'slug' => 'blood-pressure-screening-4',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-03 15:42:23',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66ebe2a713dda.png',
                'video' => NULL,
                'price' => 213.0,
                'created_at' => '2024-09-03 15:42:23',
                'updated_at' => '2024-10-02 15:38:38',
                'deleted_at' => '2024-10-02 15:38:38',
            ),
            4 => 
            array (
                'id' => 5,
                'doctor_id' => 71,
                'clinic_id' => NULL,
                'service_category_id' => 2,
                'name' => '{"en":"physiotherapy","hi":"फिजियोथेरेपी","ar":"العلاج الطبيعي"}',
                'description' => '{"en":"physiotherapy","hi":"फिजियोथेरेपी","ar":"العلاج الطبيعي"}',
                'slug' => 'physiotherapy-5',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-13 15:50:50',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66e4190a1eed2.png',
                'video' => NULL,
                'price' => 20.0,
                'created_at' => '2024-09-13 15:50:50',
                'updated_at' => '2024-10-02 15:39:51',
                'deleted_at' => '2024-10-02 15:39:51',
            ),
            5 => 
            array (
                'id' => 6,
                'doctor_id' => 60,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"Blood Tests","ar":"فحوصات الدم","hi":"रक्त परीक्षण"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ"}',
                'slug' => 'blood-tests-6',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-19 13:51:46',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66ebe622045a5.png',
                'video' => NULL,
                'price' => 20.0,
                'created_at' => '2024-09-19 13:51:46',
                'updated_at' => '2024-09-19 14:44:34',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'doctor_id' => 60,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"Urinalysis","ar":"تحليل البول","hi":"मूत्र-विश्लेषण"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ"}',
                'slug' => 'urinalysis-7',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-19 13:53:58',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66ebe6a67df0e.png',
                'video' => NULL,
                'price' => 20.0,
                'created_at' => '2024-09-19 13:53:58',
                'updated_at' => '2024-09-19 14:43:01',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'doctor_id' => 60,
                'clinic_id' => NULL,
                'service_category_id' => 2,
                'name' => '{"en":"Vision Tests","hi":"दृष्टि परीक्षण","ar":"اختبارات الرؤية"}',
                'description' => '{"ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut."}',
                'slug' => 'vision-tests-8',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-19 13:55:58',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66ebe71e5926d.png',
                'video' => NULL,
                'price' => 20.0,
                'created_at' => '2024-09-19 13:55:58',
                'updated_at' => '2024-09-19 14:41:21',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_category_id' => 3,
                'name' => '{"en":"Hearing Tests","ar":"اختبارات السمع","hi":"श्रवण परीक्षण"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ"}',
                'slug' => 'hearing-tests-9',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-19 13:58:16',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66ebe7a89efbd.png',
                'video' => NULL,
                'price' => 20.0,
                'created_at' => '2024-09-19 13:58:16',
                'updated_at' => '2024-09-19 14:15:34',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_category_id' => 2,
                'name' => '{"en":"Ultrasound","hi":"श्रवण परीक्षण","ar":"اختبارات السمع"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ"}',
                'slug' => 'ultrasound-10',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-19 14:01:53',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66ebe88131a5b.png',
                'video' => NULL,
                'price' => 30.0,
                'created_at' => '2024-09-19 14:01:53',
                'updated_at' => '2024-09-19 14:14:10',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'doctor_id' => 62,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"Allergy Testing","ar":"اختبارات السمع","hi":"श्रवण परीक्षण"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis ante ut purus eleifend vehicula. Cras vel diam elit. Nullam scelerisque, nisi sed dignissim vehicula, sapien lacus fringilla urna, at rhoncus ex lorem vitae magna. Nam fermentum, purus sed consequat vulputate, lorem sapien dictum lorem, vitae euismod augue risus non mi. In hac habitasse platea dictumst. Donec a orci mauris. Pellentesque nec sem libero. Vestibulum fringilla neque ut est efficitur aliquet. Nulla facilisi. Fusce et ligula vitae lorem cursus aliquam. Aliquam a erat a mi bibendum molestie. Phasellus ut ex a justo dignissim scelerisque sit amet sed libero. Duis egestas, mi non dapibus hendrerit, libero nunc tincidunt orci, in dignissim ex mi a augue. Donec sed nulla in elit gravida venenatis et non augue. Pellentesque et libero quis lorem convallis viverra. Etiam fermentum sapien turpis, vel posuere velit varius ut.","hi":"लोरेम इप्सम डोलर सिट अमेट, कॉन्सेकट्यूर एडिपिसिंग एलीट. प्रेज़ेंट फसिलिसिस अंते उत पुरुस एलीफेंड व्हीकुला. क्रास वेल डायम एलीट. नुल्लम स्केलरिस्क, निसी सेड डिग्निस्सिम व्हीकुला, सैपियन लकुस फ्रिंजिल्ला उरना, एट रोंकस एक्स लोरेम विटे माग्ना. नाम फेर्मेंटुम, पुरुस सेड कंसक्वाट वुल्पुटेट, लोरेम सैपियन डिक्टम लोरेम, विटे एयूसमोड औगुए रीसस नॉन मी. इन हक हबितास्से प्लाटेआ डिक्टुमस्ट. डोनेक अ ओर्की मौरिस. पेल्लेंटेस्के नेक सेम लिबरो. वेस्टिबुलम फ्रिंजिल्ला नेकुए उत एस्ट एफिकितुर अलिक्वेट. नुल्ला फासिलिसि. फ्यूस्के एट लिगुला विटे लोरेम कर्सस अलिक्वाम. आलिक्वाम अ एराट अ मि बिबेंडम मोलस्टिये. फासेल्लस उत एक्स अ जस्टो डिग्निस्सिम स्केलरिस्क सिट अमेट सेड लिबरो. डुइस एगेस्टास, मि नॉन डापिबुस हेंड्रेरिट, लिबरो नुंक टिन्सीडुंट ऑर्की, इन डिग्निस्सिम एक्स मि अ औगुए. डोनेक सेड नुल्ला इन एलीट ग्राविडा विनेनेटिस एट नॉन औगुए.","ar":"لوريم إيبسوم دولور سيت أميت، كونسكتتور أديبيسينغ إليت. بريسنت فاسيليسيس أنتي أوت بوروس إليفند فيكولا. كراس فيل ديام إليت. نولام سكيلريسكي، نيسي سيد ديغنيسيم فيكولا، سابين لاكوس فرنجيلا أورنا، أت رونكوس إكس لوريم فيتاي ماجنا. نام فيرمينتوم، بوروس سيد كونسكووت فولووتات، لوريم سابين ديكتوم لوريم، فيتاي إويسمود أوغي ريسوس نون مي. إن هاك هابيتاس بلاتيا ديكتومست. دونيك أ أوركي موريس. بيلينتسكي نيك سيم ليبيرو. فيستيبيولوم فرنجيلا نيكوي أوت إيست إفيكيتور أليكويت. نولا فاسيليسي. فوسكي إت ليجولا فيتاي لوريم كورسوس أليكوام. أليكوام أ إيرات أ مي بيبندم مولستيي. فاسيليس أوت إكس أ جوستو ديغنيسيم سكيلريسكي سيت أميت سيد ليبيرو. دويس إيغيتاس، مي نون دابيبوس هندريريت، ليبيرو ننك تنسيدونت أوركي، إن ديغنيسيم إكس مي أ أوغ"}',
                'slug' => 'allergy-testing-11',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-19 14:04:08',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66ebe9086b119.png',
                'video' => NULL,
                'price' => 30.0,
                'created_at' => '2024-09-19 14:04:08',
                'updated_at' => '2024-09-19 14:11:35',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'doctor_id' => 83,
                'clinic_id' => NULL,
                'service_category_id' => 2,
                'name' => '{"en":"hgfhfd","hi":"fdghfg","ar":"fghfd"}',
                'description' => '{"en":"fdhfg","hi":"fghfd","ar":"gfhfdhfd"}',
                'slug' => 'hgfhfd-12',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-26 11:42:54',
                'is_featured' => 0,
                'image' => '/images/doctor_services/66f5026ed9705.png',
                'video' => NULL,
                'price' => 543.0,
                'created_at' => '2024-09-26 11:42:54',
                'updated_at' => '2024-09-26 16:16:35',
                'deleted_at' => '2024-09-26 16:16:35',
            ),
            12 => 
            array (
                'id' => 13,
                'doctor_id' => NULL,
                'clinic_id' => 32,
                'service_category_id' => 2,
                'name' => '{"en":"adssa","hi":"gsadga","ar":"adsgsd"}',
                'description' => '{"en":"dgsadg","hi":"asgsa","ar":"dgsdag"}',
                'slug' => 'adssa-13',
                'is_active' => 1,
                'is_approved' => 1,
                'approved_at' => '2024-09-26 13:32:32',
                'is_featured' => 0,
                'image' => '/images/clinic_services/66f51c2085397.png',
                'video' => NULL,
                'price' => 54.0,
                'created_at' => '2024-09-26 13:32:32',
                'updated_at' => '2024-09-26 16:16:27',
                'deleted_at' => '2024-09-26 16:16:27',
            ),
            13 => 
            array (
                'id' => 14,
                'doctor_id' => 64,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"Health checkup","hi":"स्वास्थ्य जांच","ar":"فحص الصحة"}',
                'description' => '{"en":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.","hi":"लोरम इप्सम डोलर सिट अमेट, कॉन्सेक्टेटर एडिपिस्किंग एलिट। सेड डो ईयुस्मोड टेम्पर इंकिडिडुंट उट लेबोरे एट डोलोरे मैग्ना आलिक्वा। उट एनिम एड मिनिम वेनियम।","ar":"لوريم إيبسوم دولور سيت أميت، كونسيكتتور أديبيسكنغ إليت. سيد دو إيوس مود تيمبر إنكيديدنت أوت لابوري إت دولوري ماغنا أليكوا. أوت إنيم أد مينيم فينيا"}',
                'slug' => 'health-checkup-14',
                'is_active' => 1,
                'is_approved' => 0,
                'approved_at' => NULL,
                'is_featured' => 0,
                'image' => '/images/doctor_services/66fd11f343a03.png',
                'video' => NULL,
                'price' => 123.0,
                'created_at' => '2024-10-02 14:27:15',
                'updated_at' => '2024-10-02 14:44:29',
                'deleted_at' => '2024-10-02 14:44:29',
            ),
            14 => 
            array (
                'id' => 15,
                'doctor_id' => 72,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"ewrwer","hi":"qwerqwer","ar":"qwerqwe"}',
                'description' => '{"en":"werqwr","hi":"wqerqwe","ar":"rqwerqwe"}',
                'slug' => 'ewrwer-15',
                'is_active' => 1,
                'is_approved' => 0,
                'approved_at' => NULL,
                'is_featured' => 0,
                'image' => '/images/doctor_services/66fd13e70e90c.png',
                'video' => NULL,
                'price' => 324.0,
                'created_at' => '2024-10-02 14:35:35',
                'updated_at' => '2024-10-02 14:44:35',
                'deleted_at' => '2024-10-02 14:44:35',
            ),
            15 => 
            array (
                'id' => 16,
                'doctor_id' => 75,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"adsfsad","hi":"sdafasd","ar":"asdfasd"}',
                'description' => '{"en":"fasdfasd","hi":"fasdfasdf","ar":"fasdfasd"}',
                'slug' => 'adsfsad-16',
                'is_active' => 1,
                'is_approved' => 0,
                'approved_at' => NULL,
                'is_featured' => 0,
                'image' => NULL,
                'video' => NULL,
                'price' => 34.0,
                'created_at' => '2024-10-02 14:36:38',
                'updated_at' => '2024-10-02 14:44:32',
                'deleted_at' => '2024-10-02 14:44:32',
            ),
            16 => 
            array (
                'id' => 17,
                'doctor_id' => 75,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"adsfsad","hi":"sadfsad","ar":"sadfsad"}',
                'description' => '{"en":"fsadfdsa","hi":"fsadfsadf","ar":"fsdafsdaf"}',
                'slug' => 'adsfsad-17',
                'is_active' => 1,
                'is_approved' => 0,
                'approved_at' => NULL,
                'is_featured' => 0,
                'image' => NULL,
                'video' => NULL,
                'price' => 43.0,
                'created_at' => '2024-10-02 15:07:58',
                'updated_at' => '2024-10-02 15:07:58',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'doctor_id' => 64,
                'clinic_id' => NULL,
                'service_category_id' => 1,
                'name' => '{"en":"sadfs","hi":"sadfsad","ar":"dsafsadf"}',
                'description' => '{"en":"adfsadf","hi":"fsadfsa","ar":"sadfsad"}',
                'slug' => 'sadfs-18',
                'is_active' => 1,
                'is_approved' => 0,
                'approved_at' => NULL,
                'is_featured' => 0,
                'image' => NULL,
                'video' => NULL,
                'price' => 45.0,
                'created_at' => '2024-10-02 15:09:28',
                'updated_at' => '2024-10-02 15:09:28',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}