<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceFaqsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_faqs')->delete();
        
        \DB::table('service_faqs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'service_id' => 4,
                'question' => '{"ar":"asd","hi":"asd","en":"wqe"}',
                'answer' => '{"ar":"asd","hi":"asd","en":"qwe"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-03 15:42:23',
                'updated_at' => '2024-09-19 13:36:55',
                'deleted_at' => '2024-09-19 13:36:55',
            ),
            1 => 
            array (
                'id' => 2,
                'service_id' => 4,
                'question' => '{"ar":"What is the price of service?","hi":"asd","en":"What is the price of service?"}',
                'answer' => '{"ar":"The price of the service is 10$","hi":"asd","en":"The price of the service is 10$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 13:36:55',
                'updated_at' => '2024-09-19 14:47:46',
                'deleted_at' => '2024-09-19 14:47:46',
            ),
            2 => 
            array (
                'id' => 3,
                'service_id' => 6,
                'question' => '{"ar":"What is the price of this service"}',
                'answer' => '{"ar":"the price of this service is 20$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 13:51:46',
                'updated_at' => '2024-09-19 14:43:34',
                'deleted_at' => '2024-09-19 14:43:34',
            ),
            3 => 
            array (
                'id' => 4,
                'service_id' => 7,
                'question' => '{"ar":"What is the price of service?"}',
                'answer' => '{"ar":"The price of the service is 20$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 13:53:58',
                'updated_at' => '2024-09-19 14:42:09',
                'deleted_at' => '2024-09-19 14:42:09',
            ),
            4 => 
            array (
                'id' => 5,
                'service_id' => 8,
                'question' => '{"en":"What is the price of this service?"}',
                'answer' => '{"en":"Price of this service is 20$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 13:55:58',
                'updated_at' => '2024-09-19 14:40:17',
                'deleted_at' => '2024-09-19 14:40:17',
            ),
            5 => 
            array (
                'id' => 6,
                'service_id' => 9,
                'question' => '{"en":"What is the price of this service$"}',
                'answer' => '{"en":"Price of this sercvice is 20$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 13:58:16',
                'updated_at' => '2024-09-19 14:14:57',
                'deleted_at' => '2024-09-19 14:14:57',
            ),
            6 => 
            array (
                'id' => 7,
                'service_id' => 10,
                'question' => '{"en":"What is the price of this service?"}',
                'answer' => '{"en":"Price of this service is 30"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:01:53',
                'updated_at' => '2024-09-19 14:12:34',
                'deleted_at' => '2024-09-19 14:12:34',
            ),
            7 => 
            array (
                'id' => 8,
                'service_id' => 11,
                'question' => '{"en":"What is the price of this service?"}',
                'answer' => '{"en":"Price of this service is 30$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:04:08',
                'updated_at' => '2024-09-19 14:10:03',
                'deleted_at' => '2024-09-19 14:10:03',
            ),
            8 => 
            array (
                'id' => 9,
                'service_id' => 11,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"en":"Price of this service is 30$","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:10:03',
                'updated_at' => '2024-09-19 14:10:38',
                'deleted_at' => '2024-09-19 14:10:38',
            ),
            9 => 
            array (
                'id' => 10,
                'service_id' => 11,
                'question' => '{"hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:10:03',
                'updated_at' => '2024-09-19 14:10:38',
                'deleted_at' => '2024-09-19 14:10:38',
            ),
            10 => 
            array (
                'id' => 11,
                'service_id' => 11,
                'question' => '{"hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"hi":"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:10:03',
                'updated_at' => '2024-09-19 14:10:38',
                'deleted_at' => '2024-09-19 14:10:38',
            ),
            11 => 
            array (
                'id' => 12,
                'service_id' => 11,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"en":"Price of this service is 30$","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:10:38',
                'updated_at' => '2024-09-19 14:11:35',
                'deleted_at' => '2024-09-19 14:11:35',
            ),
            12 => 
            array (
                'id' => 13,
                'service_id' => 11,
                'question' => '{"hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:10:38',
                'updated_at' => '2024-09-19 14:11:35',
                'deleted_at' => '2024-09-19 14:11:35',
            ),
            13 => 
            array (
                'id' => 14,
                'service_id' => 11,
                'question' => '{"hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","en":"What types of services does the doctor specialize in?"}',
                'answer' => '{"hi":"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।","en":"The doctor specializes in family medicine, pediatrics, and preventive care. They also offer chronic disease management and wellness checkups.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:10:38',
                'updated_at' => '2024-09-19 14:11:35',
                'deleted_at' => '2024-09-19 14:11:35',
            ),
            14 => 
            array (
                'id' => 15,
                'service_id' => 11,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?","ar":"منذ متى يمارس الطبيب"}',
                'answer' => '{"en":"Price of this service is 30$","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:11:35',
                'updated_at' => '2024-09-19 14:11:35',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'service_id' => 11,
                'question' => '{"hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","en":"Is the doctor board-certified in their field?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","ar":"\\"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:11:35',
                'updated_at' => '2024-09-19 14:11:35',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'service_id' => 11,
                'question' => '{"hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","en":"What types of services does the doctor specialize in?","ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟"}',
                'answer' => '{"hi":"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।","en":"The doctor specializes in family medicine, pediatrics, and preventive care. They also offer chronic disease management and wellness checkups.\\"","ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحية.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:11:35',
                'updated_at' => '2024-09-19 14:11:35',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'service_id' => 10,
                'question' => '{"en":"What is the price of this service?"}',
                'answer' => '{"en":"Price of this service is 30"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:12:34',
                'updated_at' => '2024-09-19 14:13:18',
                'deleted_at' => '2024-09-19 14:13:18',
            ),
            18 => 
            array (
                'id' => 19,
                'service_id' => 10,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:12:34',
                'updated_at' => '2024-09-19 14:13:18',
                'deleted_at' => '2024-09-19 14:13:18',
            ),
            19 => 
            array (
                'id' => 20,
                'service_id' => 10,
                'question' => '{"en":"How long has the doctor been practicing?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:12:34',
                'updated_at' => '2024-09-19 14:13:18',
                'deleted_at' => '2024-09-19 14:13:18',
            ),
            20 => 
            array (
                'id' => 21,
                'service_id' => 10,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:13:18',
                'updated_at' => '2024-09-19 14:14:10',
                'deleted_at' => '2024-09-19 14:14:10',
            ),
            21 => 
            array (
                'id' => 22,
                'service_id' => 10,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:13:18',
                'updated_at' => '2024-09-19 14:14:10',
                'deleted_at' => '2024-09-19 14:14:10',
            ),
            22 => 
            array (
                'id' => 23,
                'service_id' => 10,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:13:18',
                'updated_at' => '2024-09-19 14:14:10',
                'deleted_at' => '2024-09-19 14:14:10',
            ),
            23 => 
            array (
                'id' => 24,
                'service_id' => 10,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?","ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟"}',
                'answer' => '{"en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\"","ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:14:10',
                'updated_at' => '2024-09-19 14:14:10',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'service_id' => 10,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","ar":"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:14:10',
                'updated_at' => '2024-09-19 14:14:10',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'service_id' => 10,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","ar":"منذ متى يمارس الطبيب؟"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:14:10',
                'updated_at' => '2024-09-19 14:14:10',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'service_id' => 9,
                'question' => '{"en":"What is the price of this service$"}',
                'answer' => '{"en":"Price of this sercvice is 20$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:14:57',
                'updated_at' => '2024-09-19 14:15:34',
                'deleted_at' => '2024-09-19 14:15:34',
            ),
            27 => 
            array (
                'id' => 28,
                'service_id' => 9,
                'question' => '{"en":"What types of services does the doctor specialize in?"}',
                'answer' => '{"en":"The doctor specializes in family medicine, pediatrics, and preventive care. They also offer chronic disease management and wellness checkups"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:14:57',
                'updated_at' => '2024-09-19 14:15:34',
                'deleted_at' => '2024-09-19 14:15:34',
            ),
            28 => 
            array (
                'id' => 29,
                'service_id' => 9,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care."}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:14:57',
                'updated_at' => '2024-09-19 14:15:34',
                'deleted_at' => '2024-09-19 14:15:34',
            ),
            29 => 
            array (
                'id' => 30,
                'service_id' => 9,
                'question' => '{"en":"What is the price of this service$","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"en":"Price of this sercvice is 20$","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:15:34',
                'updated_at' => '2024-09-19 14:15:34',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'service_id' => 9,
                'question' => '{"en":"What types of services does the doctor specialize in?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"The doctor specializes in family medicine, pediatrics, and preventive care. They also offer chronic disease management and wellness checkups","hi":"\\"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:15:34',
                'updated_at' => '2024-09-19 14:15:34',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'service_id' => 9,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.","hi":"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:15:34',
                'updated_at' => '2024-09-19 14:15:34',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'service_id' => 8,
                'question' => '{"en":"What is the price of this service?"}',
                'answer' => '{"en":"Price of this service is 20$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:40:17',
                'updated_at' => '2024-09-19 14:40:44',
                'deleted_at' => '2024-09-19 14:40:44',
            ),
            33 => 
            array (
                'id' => 34,
                'service_id' => 8,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:40:17',
                'updated_at' => '2024-09-19 14:40:44',
                'deleted_at' => '2024-09-19 14:40:44',
            ),
            34 => 
            array (
                'id' => 35,
                'service_id' => 8,
                'question' => '{"en":"What types of services does the doctor specialize in?"}',
                'answer' => '{"en":"The doctor specializes in family medicine, pediatrics, and preventive care. They also offer chronic disease management and wellness checkups.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:40:17',
                'updated_at' => '2024-09-19 14:40:44',
                'deleted_at' => '2024-09-19 14:40:44',
            ),
            35 => 
            array (
                'id' => 36,
                'service_id' => 8,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"en":"Price of this service is 20$","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:40:44',
                'updated_at' => '2024-09-19 14:41:21',
                'deleted_at' => '2024-09-19 14:41:21',
            ),
            36 => 
            array (
                'id' => 37,
                'service_id' => 8,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:40:44',
                'updated_at' => '2024-09-19 14:41:21',
                'deleted_at' => '2024-09-19 14:41:21',
            ),
            37 => 
            array (
                'id' => 38,
                'service_id' => 8,
                'question' => '{"en":"What types of services does the doctor specialize in?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"The doctor specializes in family medicine, pediatrics, and preventive care. They also offer chronic disease management and wellness checkups.\\"","hi":"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:40:44',
                'updated_at' => '2024-09-19 14:41:21',
                'deleted_at' => '2024-09-19 14:41:21',
            ),
            38 => 
            array (
                'id' => 39,
                'service_id' => 8,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?","ar":"منذ متى يمارس الطبيب"}',
                'answer' => '{"en":"Price of this service is 20$","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:41:21',
                'updated_at' => '2024-09-19 14:41:21',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'service_id' => 8,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","ar":"\\"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:41:21',
                'updated_at' => '2024-09-19 14:41:21',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'service_id' => 8,
                'question' => '{"en":"What types of services does the doctor specialize in?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟"}',
                'answer' => '{"en":"The doctor specializes in family medicine, pediatrics, and preventive care. They also offer chronic disease management and wellness checkups.\\"","hi":"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।","ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحية.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:41:21',
                'updated_at' => '2024-09-19 14:41:21',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'service_id' => 7,
                'question' => '{"ar":"What is the price of service?","en":"What is the price of this service?"}',
                'answer' => '{"ar":"The price of the service is 20$","en":"Price of this service is 30"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:42:09',
                'updated_at' => '2024-09-19 14:42:34',
                'deleted_at' => '2024-09-19 14:42:34',
            ),
            42 => 
            array (
                'id' => 43,
                'service_id' => 7,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:42:09',
                'updated_at' => '2024-09-19 14:42:34',
                'deleted_at' => '2024-09-19 14:42:34',
            ),
            43 => 
            array (
                'id' => 44,
                'service_id' => 7,
                'question' => '{"en":"How long has the doctor been practicing?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:42:09',
                'updated_at' => '2024-09-19 14:42:34',
                'deleted_at' => '2024-09-19 14:42:34',
            ),
            44 => 
            array (
                'id' => 45,
                'service_id' => 7,
                'question' => '{"ar":"What is the price of service?","en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"ar":"The price of the service is 20$","en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:42:34',
                'updated_at' => '2024-09-19 14:43:01',
                'deleted_at' => '2024-09-19 14:43:01',
            ),
            45 => 
            array (
                'id' => 46,
                'service_id' => 7,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:42:34',
                'updated_at' => '2024-09-19 14:43:01',
                'deleted_at' => '2024-09-19 14:43:01',
            ),
            46 => 
            array (
                'id' => 47,
                'service_id' => 7,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:42:34',
                'updated_at' => '2024-09-19 14:43:01',
                'deleted_at' => '2024-09-19 14:43:01',
            ),
            47 => 
            array (
                'id' => 48,
                'service_id' => 7,
                'question' => '{"ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟","en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحي","en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:43:01',
                'updated_at' => '2024-09-19 14:43:01',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'service_id' => 7,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","ar":"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:43:01',
                'updated_at' => '2024-09-19 14:43:01',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'service_id' => 7,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","ar":"منذ متى يمارس الطبيب؟"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:43:01',
                'updated_at' => '2024-09-19 14:43:01',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'service_id' => 6,
                'question' => '{"ar":"What is the price of this service","en":"What is the price of this service?"}',
                'answer' => '{"ar":"the price of this service is 20$","en":"Price of this service is 30"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:43:34',
                'updated_at' => '2024-09-19 14:44:03',
                'deleted_at' => '2024-09-19 14:44:03',
            ),
            51 => 
            array (
                'id' => 52,
                'service_id' => 6,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:43:34',
                'updated_at' => '2024-09-19 14:44:03',
                'deleted_at' => '2024-09-19 14:44:03',
            ),
            52 => 
            array (
                'id' => 53,
                'service_id' => 6,
                'question' => '{"en":"How long has the doctor been practicing?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:43:34',
                'updated_at' => '2024-09-19 14:44:03',
                'deleted_at' => '2024-09-19 14:44:03',
            ),
            53 => 
            array (
                'id' => 54,
                'service_id' => 6,
                'question' => '{"ar":"What is the price of this service","en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"ar":"the price of this service is 20$","en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:44:03',
                'updated_at' => '2024-09-19 14:44:34',
                'deleted_at' => '2024-09-19 14:44:34',
            ),
            54 => 
            array (
                'id' => 55,
                'service_id' => 6,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:44:03',
                'updated_at' => '2024-09-19 14:44:34',
                'deleted_at' => '2024-09-19 14:44:34',
            ),
            55 => 
            array (
                'id' => 56,
                'service_id' => 6,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:44:03',
                'updated_at' => '2024-09-19 14:44:34',
                'deleted_at' => '2024-09-19 14:44:34',
            ),
            56 => 
            array (
                'id' => 57,
                'service_id' => 6,
                'question' => '{"ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟","en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحي","en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:44:34',
                'updated_at' => '2024-09-19 14:44:34',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'service_id' => 6,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","ar":"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:44:34',
                'updated_at' => '2024-09-19 14:44:34',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'service_id' => 6,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","ar":"منذ متى يمارس الطبيب؟"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:44:34',
                'updated_at' => '2024-09-19 14:44:34',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'service_id' => 4,
                'question' => '{"ar":"What is the price of service?","hi":"asd","en":"What is the price of service?"}',
                'answer' => '{"ar":"The price of the service is 10$","hi":"asd","en":"The price of the service is 10$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:47:46',
                'updated_at' => '2024-09-19 14:48:11',
                'deleted_at' => '2024-09-19 14:48:11',
            ),
            60 => 
            array (
                'id' => 61,
                'service_id' => 4,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:47:46',
                'updated_at' => '2024-09-19 14:48:11',
                'deleted_at' => '2024-09-19 14:48:11',
            ),
            61 => 
            array (
                'id' => 62,
                'service_id' => 4,
                'question' => '{"en":"How long has the doctor been practicing?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:47:46',
                'updated_at' => '2024-09-19 14:48:11',
                'deleted_at' => '2024-09-19 14:48:11',
            ),
            62 => 
            array (
                'id' => 63,
                'service_id' => 4,
                'question' => '{"ar":"What is the price of service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?","en":"What is the price of service?"}',
                'answer' => '{"ar":"The price of the service is 10$","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\"","en":"The price of the service is 10$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:48:11',
                'updated_at' => '2024-09-19 14:48:36',
                'deleted_at' => '2024-09-19 14:48:36',
            ),
            63 => 
            array (
                'id' => 64,
                'service_id' => 4,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:48:11',
                'updated_at' => '2024-09-19 14:48:36',
                'deleted_at' => '2024-09-19 14:48:36',
            ),
            64 => 
            array (
                'id' => 65,
                'service_id' => 4,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:48:11',
                'updated_at' => '2024-09-19 14:48:36',
                'deleted_at' => '2024-09-19 14:48:36',
            ),
            65 => 
            array (
                'id' => 66,
                'service_id' => 4,
                'question' => '{"ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?","en":"What is the price of service?"}',
                'answer' => '{"ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحي","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\"","en":"The price of the service is 10$"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:48:36',
                'updated_at' => '2024-09-19 14:48:36',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'service_id' => 4,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","ar":"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:48:36',
                'updated_at' => '2024-09-19 14:48:36',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'service_id' => 4,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","ar":"منذ متى يمارس الطبيب؟"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:48:36',
                'updated_at' => '2024-09-19 14:48:36',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'service_id' => 3,
                'question' => '{"en":"What is the price of this service?"}',
                'answer' => '{"en":"Price of this service is 30"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:50:19',
                'updated_at' => '2024-09-19 14:51:03',
                'deleted_at' => '2024-09-19 14:51:03',
            ),
            69 => 
            array (
                'id' => 70,
                'service_id' => 3,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:50:19',
                'updated_at' => '2024-09-19 14:51:03',
                'deleted_at' => '2024-09-19 14:51:03',
            ),
            70 => 
            array (
                'id' => 71,
                'service_id' => 3,
                'question' => '{"en":"How long has the doctor been practicing?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:50:19',
                'updated_at' => '2024-09-19 14:51:03',
                'deleted_at' => '2024-09-19 14:51:03',
            ),
            71 => 
            array (
                'id' => 72,
                'service_id' => 3,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:03',
                'updated_at' => '2024-09-19 14:51:27',
                'deleted_at' => '2024-09-19 14:51:27',
            ),
            72 => 
            array (
                'id' => 73,
                'service_id' => 3,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:03',
                'updated_at' => '2024-09-19 14:51:27',
                'deleted_at' => '2024-09-19 14:51:27',
            ),
            73 => 
            array (
                'id' => 74,
                'service_id' => 3,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:03',
                'updated_at' => '2024-09-19 14:51:27',
                'deleted_at' => '2024-09-19 14:51:27',
            ),
            74 => 
            array (
                'id' => 75,
                'service_id' => 3,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?","ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟"}',
                'answer' => '{"en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\"","ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:27',
                'updated_at' => '2024-09-19 14:51:27',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'service_id' => 3,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","ar":"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:27',
                'updated_at' => '2024-09-19 14:51:27',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'service_id' => 3,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","ar":"منذ متى يمارس الطبيب؟"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:27',
                'updated_at' => '2024-09-19 14:51:27',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'service_id' => 2,
                'question' => '{"en":"What is the price of this service?"}',
                'answer' => '{"en":"Price of this service is 30"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:58',
                'updated_at' => '2024-09-19 14:52:23',
                'deleted_at' => '2024-09-19 14:52:23',
            ),
            78 => 
            array (
                'id' => 79,
                'service_id' => 2,
                'question' => '{"en":"Is the doctor board-certified in their field?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:58',
                'updated_at' => '2024-09-19 14:52:23',
                'deleted_at' => '2024-09-19 14:52:23',
            ),
            79 => 
            array (
                'id' => 80,
                'service_id' => 2,
                'question' => '{"en":"How long has the doctor been practicing?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:51:58',
                'updated_at' => '2024-09-19 14:52:23',
                'deleted_at' => '2024-09-19 14:52:23',
            ),
            80 => 
            array (
                'id' => 81,
                'service_id' => 2,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?"}',
                'answer' => '{"en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:52:23',
                'updated_at' => '2024-09-19 14:52:51',
                'deleted_at' => '2024-09-19 14:52:51',
            ),
            81 => 
            array (
                'id' => 82,
                'service_id' => 2,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:52:23',
                'updated_at' => '2024-09-19 14:52:51',
                'deleted_at' => '2024-09-19 14:52:51',
            ),
            82 => 
            array (
                'id' => 83,
                'service_id' => 2,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\""}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:52:23',
                'updated_at' => '2024-09-19 14:52:51',
                'deleted_at' => '2024-09-19 14:52:51',
            ),
            83 => 
            array (
                'id' => 84,
                'service_id' => 2,
                'question' => '{"en":"What is the price of this service?","hi":"डॉक्टर किस प्रकार की सेवाओं में विशेषज्ञता रखते हैं?","ar":"ما هي الخدمات التي يتخصص فيها الطبيب؟"}',
                'answer' => '{"en":"Price of this service is 30","hi":"डॉक्टर परिवार चिकित्सा, बाल रोग और पूर्वकालीन देखभाल में विशेषज्ञता रखते हैं। वे पुरानी बीमारियों का प्रबंधन और स्वास्थ्य जांच भी करते हैं।\\"","ar":"يتخصص الطبيب في الطب العائلي، وطب الأطفال، والرعاية الوقائية. كما يقدم إدارة الأمراض المزمنة والفحوصات الصحي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:52:51',
                'updated_at' => '2024-09-19 14:52:51',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'service_id' => 2,
                'question' => '{"en":"Is the doctor board-certified in their field?","hi":"क्या डॉक्टर अपनी क्षेत्र में बोर्ड-सर्टिफाइड हैं?","ar":"هل الطبيب معتمد من المجلس في مجاله؟"}',
                'answer' => '{"en":"Yes, the doctor is board-certified in internal medicine and has additional certification in geriatric care.\\"","hi":"हां, डॉक्टर आंतरिक चिकित्सा में बोर्ड-सर्टिफाइड हैं और वृद्धाश्रम देखभाल में अतिरिक्त प्रमाणन प्राप्त किया है।\\"","ar":"نعم، الطبيب معتمد من المجلس في الطب الداخلي ولديه شهادة إضافية في الرعاية"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:52:51',
                'updated_at' => '2024-09-19 14:52:51',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'service_id' => 2,
                'question' => '{"en":"How long has the doctor been practicing?","hi":"डॉक्टर ने कितने वर्षों से अभ्यास किया है?","ar":"منذ متى يمارس الطبيب؟"}',
                'answer' => '{"en":"The doctor has been practicing for over 15 years, with extensive experience in both private practice and hospital settings","hi":"\\"डॉक्टर ने 15 वर्षों से अधिक समय से अभ्यास किया है, निजी प्रैक्टिस और अस्पताल सेटिंग्स दोनों में व्यापक अनुभव है।\\"","ar":"لقد مارس الطبيب مهنة الطب لأكثر من 15 عامًا، ولديه خبرة واسعة في كل من الممارسات الخاصة والإعدادات المستشفوي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-19 14:52:51',
                'updated_at' => '2024-09-19 14:52:51',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'service_id' => 12,
                'question' => '{"en":"dffdsfdfs"}',
                'answer' => '{"en":"gsfdgdgdsf"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-09-26 11:42:54',
                'updated_at' => '2024-09-26 11:42:54',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:27:15',
                'updated_at' => '2024-10-02 14:29:03',
                'deleted_at' => '2024-10-02 14:29:03',
            ),
            88 => 
            array (
                'id' => 89,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:27:15',
                'updated_at' => '2024-10-02 14:29:03',
                'deleted_at' => '2024-10-02 14:29:03',
            ),
            89 => 
            array (
                'id' => 90,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:27:15',
                'updated_at' => '2024-10-02 14:29:03',
                'deleted_at' => '2024-10-02 14:29:03',
            ),
            90 => 
            array (
                'id' => 91,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:29:03',
                'updated_at' => '2024-10-02 14:29:53',
                'deleted_at' => '2024-10-02 14:29:53',
            ),
            91 => 
            array (
                'id' => 92,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:29:03',
                'updated_at' => '2024-10-02 14:29:53',
                'deleted_at' => '2024-10-02 14:29:53',
            ),
            92 => 
            array (
                'id' => 93,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:29:03',
                'updated_at' => '2024-10-02 14:29:53',
                'deleted_at' => '2024-10-02 14:29:53',
            ),
            93 => 
            array (
                'id' => 94,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:29:53',
                'updated_at' => '2024-10-02 14:30:28',
                'deleted_at' => '2024-10-02 14:30:28',
            ),
            94 => 
            array (
                'id' => 95,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:29:53',
                'updated_at' => '2024-10-02 14:30:28',
                'deleted_at' => '2024-10-02 14:30:28',
            ),
            95 => 
            array (
                'id' => 96,
                'service_id' => 14,
                'question' => '[]',
                'answer' => '[]',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:29:53',
                'updated_at' => '2024-10-02 14:30:28',
                'deleted_at' => '2024-10-02 14:30:28',
            ),
            96 => 
            array (
                'id' => 97,
                'service_id' => 14,
                'question' => '{"en":"What is included in a standard health checkup?"}',
                'answer' => '{"en":"A standard health checkup typically includes blood tests, urine tests, blood pressure measurement, cholesterol levels, and a physical examination."}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:30:28',
                'updated_at' => '2024-10-02 14:31:20',
                'deleted_at' => '2024-10-02 14:31:20',
            ),
            97 => 
            array (
                'id' => 98,
                'service_id' => 14,
                'question' => '{"en":"How often should I get a health checkup?"}',
                'answer' => '{"en":"It is generally recommended to have a health checkup once a year, but individuals with specific health concerns should consult their doctor for personalized advice."}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:30:28',
                'updated_at' => '2024-10-02 14:31:20',
                'deleted_at' => '2024-10-02 14:31:20',
            ),
            98 => 
            array (
                'id' => 99,
                'service_id' => 14,
                'question' => '{"en":"What should I prepare for my health checkup?"}',
                'answer' => '{"en":"It’s best to fast for at least 8-12 hours before blood tests, bring any medical history documents, and prepare a list of current medications."}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:30:28',
                'updated_at' => '2024-10-02 14:31:20',
                'deleted_at' => '2024-10-02 14:31:20',
            ),
            99 => 
            array (
                'id' => 100,
                'service_id' => 14,
                'question' => '{"en":"What is included in a standard health checkup?","hi":"मुझे अपनी स्वास्थ्य जांच के लिए क्या तैयारी करनी चाहिए?"}',
                'answer' => '{"en":"A standard health checkup typically includes blood tests, urine tests, blood pressure measurement, cholesterol levels, and a physical examination.","hi":"रक्त परीक्षण से पहले कम से कम 8-12 घंटे उपवास करना सबसे अच्छा है, कोई भी चिकित्सा इतिहास दस्तावेज लाना और वर्तमान दवाओं की एक सूची तैयार करना चाहिए।"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:31:20',
                'updated_at' => '2024-10-02 14:33:41',
                'deleted_at' => '2024-10-02 14:33:41',
            ),
        ));
        \DB::table('service_faqs')->insert(array (
            0 => 
            array (
                'id' => 101,
                'service_id' => 14,
                'question' => '{"en":"How often should I get a health checkup?","hi":"मुझे कितनी बार स्वास्थ्य जांच करानी चाहिए?"}',
                'answer' => '{"en":"It is generally recommended to have a health checkup once a year, but individuals with specific health concerns should consult their doctor for personalized advice.","hi":"सामान्यतः, स्वास्थ्य जांच साल में एक बार कराना उचित होता है, लेकिन जिन व्यक्तियों को विशेष स्वास्थ्य चिंताएँ हैं, उन्हें व्यक्तिगत सलाह के लिए अपने डॉक्टर से परामर्श करना चाहिए।"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:31:20',
                'updated_at' => '2024-10-02 14:33:41',
                'deleted_at' => '2024-10-02 14:33:41',
            ),
            1 => 
            array (
                'id' => 102,
                'service_id' => 14,
                'question' => '{"en":"What should I prepare for my health checkup?","hi":"एक मानक स्वास्थ्य जांच में क्या शामिल होता है?"}',
                'answer' => '{"en":"It’s best to fast for at least 8-12 hours before blood tests, bring any medical history documents, and prepare a list of current medications.","hi":"एक मानक स्वास्थ्य जांच में आमतौर पर रक्त परीक्षण, मूत्र परीक्षण, रक्त दबाव मापना, कोलेस्ट्रॉल स्तर, और शारीरिक परीक्षा शामिल होती है।"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:31:20',
                'updated_at' => '2024-10-02 14:33:41',
                'deleted_at' => '2024-10-02 14:33:41',
            ),
            2 => 
            array (
                'id' => 103,
                'service_id' => 14,
                'question' => '{"en":"What is included in a standard health checkup?","hi":"मुझे अपनी स्वास्थ्य जांच के लिए क्या तैयारी करनी चाहिए?","ar":"ماذا يتضمن الفحص الصحي القياسي؟"}',
                'answer' => '{"en":"A standard health checkup typically includes blood tests, urine tests, blood pressure measurement, cholesterol levels, and a physical examination.","hi":"रक्त परीक्षण से पहले कम से कम 8-12 घंटे उपवास करना सबसे अच्छा है, कोई भी चिकित्सा इतिहास दस्तावेज लाना और वर्तमान दवाओं की एक सूची तैयार करना चाहिए।","ar":"يتضمن الفحص الصحي القياسي عادةً اختبارات الدم، اختبارات البول، قياس ضغط الدم، مستويات الكوليسترول، وفحصًا جسديً"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:33:41',
                'updated_at' => '2024-10-02 14:33:41',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 104,
                'service_id' => 14,
                'question' => '{"en":"How often should I get a health checkup?","hi":"मुझे कितनी बार स्वास्थ्य जांच करानी चाहिए?","ar":"كم مرة يجب أن أجري فحصًا صحيًا؟"}',
                'answer' => '{"en":"It is generally recommended to have a health checkup once a year, but individuals with specific health concerns should consult their doctor for personalized advice.","hi":"सामान्यतः, स्वास्थ्य जांच साल में एक बार कराना उचित होता है, लेकिन जिन व्यक्तियों को विशेष स्वास्थ्य चिंताएँ हैं, उन्हें व्यक्तिगत सलाह के लिए अपने डॉक्टर से परामर्श करना चाहिए।","ar":"يُوصى عمومًا بإجراء الفحص الصحي مرة واحدة في السنة، ولكن يجب على الأفراد الذين لديهم مخاوف صحية محددة استشارة طبيبهم للحصول على نصائح مخصص"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:33:41',
                'updated_at' => '2024-10-02 14:33:41',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 105,
                'service_id' => 14,
                'question' => '{"en":"What should I prepare for my health checkup?","hi":"एक मानक स्वास्थ्य जांच में क्या शामिल होता है?","ar":"ماذا يجب أن أعد لفحصي الصحي؟"}',
                'answer' => '{"en":"It’s best to fast for at least 8-12 hours before blood tests, bring any medical history documents, and prepare a list of current medications.","hi":"एक मानक स्वास्थ्य जांच में आमतौर पर रक्त परीक्षण, मूत्र परीक्षण, रक्त दबाव मापना, कोलेस्ट्रॉल स्तर, और शारीरिक परीक्षा शामिल होती है।","ar":"من الأفضل الصيام لمدة 8-12 ساعة على الأقل قبل اختبارات الدم، وإحضار أي مستندات تاريخ طبي، وإعداد قائمة بالأدوية الحالي"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:33:41',
                'updated_at' => '2024-10-02 14:33:41',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 106,
                'service_id' => 15,
                'question' => '{"en":"qwer"}',
                'answer' => '{"en":"wqerwq"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 14:35:35',
                'updated_at' => '2024-10-02 14:35:35',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 107,
                'service_id' => 17,
                'question' => '{"en":"sdafsd"}',
                'answer' => '{"en":"fasdf"}',
                'is_active' => 1,
                'sort_order' => NULL,
                'image' => NULL,
                'created_at' => '2024-10-02 15:07:58',
                'updated_at' => '2024-10-02 15:07:58',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}