<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('transactions')->delete();
        
        \DB::table('transactions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 3,
                'wallet_id' => 1,
                'type' => 'deposit',
                'amount' => '50',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 25"}',
                'uuid' => '8dfd9229-d7e9-41a8-8726-ee44ab80e351',
                'created_at' => '2024-09-23 16:19:53',
                'updated_at' => '2024-09-23 16:19:53',
            ),
            1 => 
            array (
                'id' => 2,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 3,
                'wallet_id' => 1,
                'type' => 'deposit',
                'amount' => '50',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 29"}',
                'uuid' => 'e23a7492-5ca8-48cb-b488-0f7621a573d7',
                'created_at' => '2024-09-26 14:14:31',
                'updated_at' => '2024-09-26 14:14:31',
            ),
            2 => 
            array (
                'id' => 3,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 120,
                'wallet_id' => 5,
                'type' => 'deposit',
                'amount' => '32',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 30"}',
                'uuid' => '8a0e1256-f58c-4f5b-89f5-14c4b7b9abf6',
                'created_at' => '2024-09-26 14:40:01',
                'updated_at' => '2024-09-26 14:40:01',
            ),
            3 => 
            array (
                'id' => 4,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 125,
                'wallet_id' => 6,
                'type' => 'deposit',
                'amount' => '32',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 31"}',
                'uuid' => 'd99a3ef3-44f6-4a8a-901b-8285f1ecb193',
                'created_at' => '2024-09-26 18:43:12',
                'updated_at' => '2024-09-26 18:43:12',
            ),
            4 => 
            array (
                'id' => 5,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 127,
                'wallet_id' => 7,
                'type' => 'deposit',
                'amount' => '234',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 32"}',
                'uuid' => '5f37d970-5954-4233-802e-f0ce7289064f',
                'created_at' => '2024-09-26 18:54:24',
                'updated_at' => '2024-09-26 18:54:24',
            ),
            5 => 
            array (
                'id' => 6,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 160,
                'wallet_id' => 9,
                'type' => 'deposit',
                'amount' => '100',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion"}',
                'uuid' => '75bdb4da-f324-4c06-8340-8567775fadd8',
                'created_at' => '2024-09-27 15:55:31',
                'updated_at' => '2024-09-27 15:55:31',
            ),
            6 => 
            array (
                'id' => 7,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 160,
                'wallet_id' => 9,
                'type' => 'deposit',
                'amount' => '20',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion"}',
                'uuid' => '8ec83953-2878-4dfc-b384-afb2f82ad152',
                'created_at' => '2024-09-27 19:08:34',
                'updated_at' => '2024-09-27 19:08:34',
            ),
            7 => 
            array (
                'id' => 8,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 161,
                'wallet_id' => 8,
                'type' => 'deposit',
                'amount' => '30',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion"}',
                'uuid' => '65e96488-c59f-477d-8db2-0772570d382d',
                'created_at' => '2024-09-27 19:25:25',
                'updated_at' => '2024-09-27 19:25:25',
            ),
            8 => 
            array (
                'id' => 9,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 161,
                'wallet_id' => 8,
                'type' => 'withdraw',
                'amount' => '-30',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Appointment Booked through Wallet"}',
                'uuid' => '9292d7fd-6300-4bf2-bd83-2d6ffb82207a',
                'created_at' => '2024-10-01 14:22:30',
                'updated_at' => '2024-10-01 14:22:30',
            ),
            9 => 
            array (
                'id' => 10,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 161,
                'wallet_id' => 8,
                'type' => 'deposit',
                'amount' => '50',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"stripe payment deposite"}',
                'uuid' => 'c706179d-02d8-46e1-991c-602391dbf04a',
                'created_at' => '2024-10-01 14:45:18',
                'updated_at' => '2024-10-01 14:45:18',
            ),
            10 => 
            array (
                'id' => 11,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 113,
                'wallet_id' => 2,
                'type' => 'deposit',
                'amount' => '20',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"stripe payment deposite"}',
                'uuid' => 'e0fc8afc-88b6-4102-9f69-262201ef9c98',
                'created_at' => '2024-10-01 18:03:09',
                'updated_at' => '2024-10-01 18:03:09',
            ),
            11 => 
            array (
                'id' => 12,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 161,
                'wallet_id' => 8,
                'type' => 'withdraw',
                'amount' => '-10',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Appointment Booked through Wallet"}',
                'uuid' => '299f1118-69c3-46ec-af8c-ebc7a31aaad6',
                'created_at' => '2024-10-02 17:08:57',
                'updated_at' => '2024-10-02 17:08:57',
            ),
            12 => 
            array (
                'id' => 13,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 161,
                'wallet_id' => 8,
                'type' => 'withdraw',
                'amount' => '-30',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Appointment Booked through Wallet"}',
                'uuid' => '1390686a-132a-44d7-a76f-859af375230f',
                'created_at' => '2024-10-03 15:22:24',
                'updated_at' => '2024-10-03 15:22:24',
            ),
            13 => 
            array (
                'id' => 14,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 165,
                'wallet_id' => 12,
                'type' => 'deposit',
                'amount' => '100',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"stripe payment deposite"}',
                'uuid' => '85536829-21b9-4b92-b6f0-868801f086a4',
                'created_at' => '2024-10-03 18:03:22',
                'updated_at' => '2024-10-03 18:03:22',
            ),
            14 => 
            array (
                'id' => 15,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 165,
                'wallet_id' => 12,
                'type' => 'withdraw',
                'amount' => '-50',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Appointment Booked through Wallet"}',
                'uuid' => 'd3c0af5d-6032-49ab-be23-fa0dbe368b46',
                'created_at' => '2024-10-03 18:10:08',
                'updated_at' => '2024-10-03 18:10:08',
            ),
            15 => 
            array (
                'id' => 16,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 120,
                'wallet_id' => 5,
                'type' => 'deposit',
                'amount' => '20',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Service # 14"}',
                'uuid' => '4b1375d9-cc45-4a4f-a10b-3e8902a4c760',
                'created_at' => '2024-10-04 15:38:57',
                'updated_at' => '2024-10-04 15:38:57',
            ),
            16 => 
            array (
                'id' => 17,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 120,
                'wallet_id' => 5,
                'type' => 'deposit',
                'amount' => '20',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Service # 3"}',
                'uuid' => '223228c5-a849-44d9-bdde-b7c6096f6d8a',
                'created_at' => '2024-10-04 18:20:44',
                'updated_at' => '2024-10-04 18:20:44',
            ),
            17 => 
            array (
                'id' => 18,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 167,
                'wallet_id' => 13,
                'type' => 'deposit',
                'amount' => '35',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"stripe payment deposite"}',
                'uuid' => '77b258a1-f1fa-4323-b524-ac72c770f792',
                'created_at' => '2024-10-05 21:06:07',
                'updated_at' => '2024-10-05 21:06:07',
            ),
            18 => 
            array (
                'id' => 19,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 167,
                'wallet_id' => 13,
                'type' => 'withdraw',
                'amount' => '-34',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Appointment Booked through Wallet"}',
                'uuid' => 'f2a9196f-51c0-4a52-9430-5c8cd13e8153',
                'created_at' => '2024-10-05 21:06:20',
                'updated_at' => '2024-10-05 21:06:20',
            ),
            19 => 
            array (
                'id' => 20,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 167,
                'wallet_id' => 13,
                'type' => 'deposit',
                'amount' => '3423',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion"}',
                'uuid' => 'ccb5c1c6-62e3-4c81-89b7-51775734b186',
                'created_at' => '2024-10-05 21:09:16',
                'updated_at' => '2024-10-05 21:09:16',
            ),
            20 => 
            array (
                'id' => 21,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 120,
                'wallet_id' => 5,
                'type' => 'deposit',
                'amount' => '3423',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 58"}',
                'uuid' => '58828c7f-2a06-4ab4-8945-33f7f4bdcc4f',
                'created_at' => '2024-10-05 21:46:02',
                'updated_at' => '2024-10-05 21:46:02',
            ),
            21 => 
            array (
                'id' => 22,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 120,
                'wallet_id' => 5,
                'type' => 'deposit',
                'amount' => '32',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 57"}',
                'uuid' => 'af161680-7698-4da5-927b-434892e2ed5a',
                'created_at' => '2024-10-05 21:47:04',
                'updated_at' => '2024-10-05 21:47:04',
            ),
            22 => 
            array (
                'id' => 23,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 120,
                'wallet_id' => 5,
                'type' => 'deposit',
                'amount' => '34',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Appointment # 59"}',
                'uuid' => 'a1e5dcfc-ff0c-46fd-8cc8-ce17ded5d7b0',
                'created_at' => '2024-10-05 21:53:28',
                'updated_at' => '2024-10-05 21:53:28',
            ),
            23 => 
            array (
                'id' => 24,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 168,
                'wallet_id' => 14,
                'type' => 'deposit',
                'amount' => '50',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"stripe payment deposite"}',
                'uuid' => '7afa8449-76b9-4649-9c4d-e16b68d43d99',
                'created_at' => '2024-10-07 12:13:20',
                'updated_at' => '2024-10-07 12:13:20',
            ),
            24 => 
            array (
                'id' => 25,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 168,
                'wallet_id' => 14,
                'type' => 'withdraw',
                'amount' => '-30',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Appointment Booked through Wallet"}',
                'uuid' => '323c6098-43fc-404e-ac54-7581b33678bf',
                'created_at' => '2024-10-07 12:18:29',
                'updated_at' => '2024-10-07 12:18:29',
            ),
            25 => 
            array (
                'id' => 26,
                'payable_type' => 'App\\Models\\User',
                'payable_id' => 3,
                'wallet_id' => 1,
                'type' => 'deposit',
                'amount' => '30',
                'confirmed' => 1,
                'details' => NULL,
                'meta' => '{"details":"Deposit on Completion of Service # 20"}',
                'uuid' => '29ccdbde-846b-47c0-aba5-90e32f754989',
                'created_at' => '2024-10-07 18:16:35',
                'updated_at' => '2024-10-07 18:16:35',
            ),
        ));
        
        
    }
}