<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Super Admin',
                'email' => 'superadmin@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2022-01-28 15:16:30',
                'password' => '$2y$10$xrrNTKRn4sK9xlSZOtKrXOtbHLhX5nUHETX2NbJqDbKcvTjkbfWMK',
            'profile_image_path' => '/profile_images/1690905720download (2).jpeg',
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-08-03 11:43:37',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'name' => 'Doctor Profile',
                'email' => 'doctor@doctor.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-03 15:45:50',
                'password' => '$2y$10$7Cf/DNx3d2xlgBPVXC2Z9.33L4jv0XKBfETYpfiRbwNx.QbrIzhiO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-03 15:45:50',
                'updated_at' => '2023-08-03 15:45:50',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 58,
                'name' => 'Consultant Doctor',
                'email' => 'consultant@doctor.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-23 18:32:53',
                'password' => '$2y$10$cCCjbt1e9QBXg3zlwPPNpeI7nSS7vnjwNBf0MyeCQci7/W8sDbI1e',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-23 18:32:53',
                'updated_at' => '2023-11-23 18:32:53',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 112,
                'name' => 'Clinic Consultant',
                'email' => 'clinic@doctor.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-08 12:25:45',
                'password' => '$2y$10$dBWGHZZgdO3iQSWL0Yzdme5u0FRei5T0/j2RnuHBeOLqAXrHag1TG',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-08 12:25:45',
                'updated_at' => '2024-07-08 12:25:45',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 113,
                'name' => 'Patient Consultant',
                'email' => 'patient@doctor.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-08 12:30:31',
                'password' => '$2y$10$c1Bv6zLuqNJVMtLY0dKKGuVNrn5Cb1VJPcfK3l1TK6zFgQfO6mz5C',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-08 12:30:31',
                'updated_at' => '2024-07-08 12:30:31',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 114,
                'name' => 'Naveed Mughal',
                'email' => 'naveedmughal@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-10 07:55:39',
                'password' => '$2y$10$3bySP/JjRAMBfgwi9hrb2ukdRPGGpvAtuaGxlF0RvLLlvoWtgU05S',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-10 07:55:39',
                'updated_at' => '2024-07-10 07:55:39',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 115,
                'name' => 'Mahad Baig',
                'email' => 'mahadbaig@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-10 08:02:24',
                'password' => '$2y$10$brLBIxpPKCtAWj8f2eHaX.r4G4.Gw4lTcKUgroYUIfKZ7twv7NBhi',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-10 08:02:24',
                'updated_at' => '2024-07-10 08:02:24',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 116,
                'name' => 'Talha Talha',
                'email' => 'talha@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-10 08:11:11',
                'password' => '$2y$10$FzclNCP4oBRG03LbydviGuYWuLeDdafRynNdm.m1m2sKnhBP1/XaK',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-10 08:11:11',
                'updated_at' => '2024-07-10 08:11:11',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 117,
                'name' => 'Buffy Delacruz',
                'email' => 'garixebyc@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-10 08:35:24',
                'password' => '$2y$10$JAJtir1BiOppBEqp5Aat1uwo3w77ZuAIOFoPkSYAE6AKw/9ioMoKG',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-10 08:35:24',
                'updated_at' => '2024-07-10 08:35:24',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 118,
                'name' => 'Alexander James',
                'email' => 'Alexander112@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 15:52:20',
                'password' => '$2y$10$klwpEXAdNzNcMspKSDHoteSlz5aZ56qGXhwibPyU15BSGw260fZhe',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 15:52:20',
                'updated_at' => '2024-07-24 15:52:20',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 119,
                'name' => 'Naveed Amin',
                'email' => 'naveed@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 15:56:15',
                'password' => '$2y$10$gGhkX9HcUP2A.TuVN623qeDBt7YdxTnz26QLeV24dzsKdRvhytRRi',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 15:56:15',
                'updated_at' => '2024-07-24 15:56:15',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 120,
                'name' => 'Alexander James',
                'email' => 'Alexander1122@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 15:57:22',
                'password' => '$2y$10$7tBQBC8rfDQjXDmLI8WIb.7VYWNJ0Z///v2oiZfffW4bXxm01pvkG',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 15:57:22',
                'updated_at' => '2024-07-24 15:57:22',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 121,
                'name' => 'Health Quest',
                'email' => 'health@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 15:59:02',
                'password' => '$2y$10$MCTn.FEiFrOA/G5mt/2SW.sFTo.xPgWNWipAjcTgGdGZour144vnu',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 15:59:01',
                'updated_at' => '2024-07-24 15:59:02',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 122,
                'name' => 'John Doe',
                'email' => 'john@doe.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 16:01:40',
                'password' => '$2y$10$mJA/UgnXJXOPX9mPetaT5.4ewTHNE8b7k2DJZ2JgKESuZBTz/3vFu',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 16:01:40',
                'updated_at' => '2024-07-24 16:01:40',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 123,
                'name' => 'Health Quest',
                'email' => 'quest@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 16:04:36',
                'password' => '$2y$10$I1/meBs878hTRZ6jviYQIO8NafpABnWpjDxdEI5LE2WiYxSodpyTe',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 16:04:36',
                'updated_at' => '2024-07-24 16:04:36',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 124,
                'name' => 'Miguel John',
                'email' => 'miguel1122@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 16:16:43',
                'password' => '$2y$10$lKcdVAGneCS04jm7PMRulOQjsH8DrKfYeiYCA3nVBzwazNbfTRh7.',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 16:16:43',
                'updated_at' => '2024-07-24 16:16:43',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 125,
                'name' => 'luther Amrik',
                'email' => 'luther1122@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 16:31:51',
                'password' => '$2y$10$kb2IqRclMLza0ClC5afxCea8t7ZkSYlAOm/wFrNNE6tAk7blPXDxm',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 16:31:51',
                'updated_at' => '2024-07-24 16:31:51',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 126,
                'name' => 'Jonathan Hughs',
                'email' => 'jonathan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 16:35:48',
                'password' => '$2y$10$WXAr/zADDdWskuFYBKS9m.n148wM/hpaqSdCIqKk9g0ZQgG4OTePC',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 16:35:48',
                'updated_at' => '2024-07-24 16:35:48',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 127,
                'name' => 'Chris Morgan',
                'email' => 'chris@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 16:39:45',
                'password' => '$2y$10$N2tP/fiS5oSTmxXOpMFbZ.51u6Fl01oHO4PyO2JNQXpH/zJXUdyBe',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 16:39:45',
                'updated_at' => '2024-07-24 16:39:45',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 128,
                'name' => 'Emily Rose',
                'email' => 'Emily1122@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 16:48:25',
                'password' => '$2y$10$kB5f5FpQZbAndawhyNWcbOLO9KHhz8FdW8DUiPFqqv6YLPGLEQAZO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 16:48:25',
                'updated_at' => '2024-07-24 16:48:25',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 129,
                'name' => 'TeleHealth Clinic',
                'email' => 'tale@health.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-24 17:40:59',
                'password' => '$2y$10$D9o5ngkQYRnftGR3Wwj3befRe2Lg75wmpym637Fr055.v0f6WgxNO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-24 17:40:59',
                'updated_at' => '2024-07-24 17:40:59',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 130,
                'name' => 'asd asdas',
                'email' => 'sophia@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-25 16:46:55',
                'password' => '$2y$10$JFM57kPyC2ykRbwIhIJiW.WrjMSPf.eZoPgEpM3U2Flr22sCbx0im',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-25 16:46:55',
                'updated_at' => '2024-07-25 16:46:55',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 131,
                'name' => 'Serenity Medical Clinic',
                'email' => 'medical1@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-25 17:59:46',
                'password' => '$2y$10$JE/j7muqXDaQCvCBaPNHX.2TGy21ErNsx6klzxfuoAEVZfO2wTDbC',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-25 17:59:46',
                'updated_at' => '2024-07-25 17:59:46',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 132,
                'name' => 'Tranquil Wellness',
                'email' => 'medical2@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-25 18:01:30',
                'password' => '$2y$10$HahKFVhKBBto3WyT3HFfTORM0tShmYaCDJEGi.8Hbo2ysSmbzYECO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-25 18:01:30',
                'updated_at' => '2024-07-25 18:01:30',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 133,
                'name' => 'dsfasd asdfs',
                'email' => 'asdf@asds',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-29 19:09:20',
                'password' => '$2y$10$Op1Qq7wRizjHWnbUzcLSpO5uK53m8OjkmPy/NswxWadMYxRmwFIQO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-29 19:09:20',
                'updated_at' => '2024-07-29 19:09:20',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 134,
                'name' => 'Faizan James',
                'email' => 'faizan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-30 15:41:23',
                'password' => '$2y$10$OtTnbpGTa/H3kvC1JXy18.4geUGI3sGzKmbnST5GJNJ7xuGJqUbkS',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-30 15:41:23',
                'updated_at' => '2024-07-30 15:41:23',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 135,
                'name' => 'John walton',
                'email' => 'john@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-07-30 18:53:26',
                'password' => '$2y$10$Zk6rpYh/jUX3uoTID8t9K.p8MCEdyWduFRnqCDrHi6Iy62GuI8suS',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-07-30 18:53:26',
                'updated_at' => '2024-07-30 18:53:26',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 136,
                'name' => 'Harry Potter',
                'email' => 'harry@potter.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-08-01 16:02:18',
                'password' => '$2y$10$jfiy.9FNOXB9SttJpB2uyOfRQALsAQmImRnVmQ6KMQuKMxai9Fv9e',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-08-01 16:02:18',
                'updated_at' => '2024-08-01 16:02:18',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 137,
                'name' => 'James Daniel',
                'email' => 'james@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 13:32:16',
                'password' => '$2y$10$5LWsVTuqbQCXaGtNgl8gQ.2MudaM.4J6h/OjuK1Msh2BWOnn57IiW',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 13:32:16',
                'updated_at' => '2024-09-16 13:32:16',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 138,
                'name' => 'Linker Lee',
                'email' => 'linker@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 14:00:10',
                'password' => '$2y$10$I9BY0zZPNYNlQsS79hA3nOHjINLb0AIYbSN1xj5dEvS82RuVlbW2.',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 14:00:10',
                'updated_at' => '2024-09-16 14:00:10',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 139,
                'name' => 'Morgan Hughes',
                'email' => 'morgan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 14:07:14',
                'password' => '$2y$10$eLvPpn8QzaQLlBBhfMGxTuaDXZGMESXBhv00jiOonkI1tXhhwhx9W',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 14:07:14',
                'updated_at' => '2024-09-16 14:07:14',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 140,
                'name' => 'Jack wade',
                'email' => 'jack@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 14:12:07',
                'password' => '$2y$10$b8xIAafSTgasxvik8dIjO.lnZZE6qGzRsQFrgCrFlqz7WeYWIcyWe',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 14:12:07',
                'updated_at' => '2024-09-16 14:12:07',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 141,
                'name' => 'Matthew Doe',
                'email' => 'matthew@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 14:16:46',
                'password' => '$2y$10$6/YIRNucAQxobN0uvNWXzeby6/CHM79D7brdKe.M2laCbxw.G/I0C',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 14:16:46',
                'updated_at' => '2024-09-16 14:16:46',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 142,
                'name' => 'Adaline lee',
                'email' => 'adaline@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 14:24:08',
                'password' => '$2y$10$3I9SITleoAHgYOjFMP7F2uexz9JdL/xZpcyZvzc1mtCQnLFaQvZ/y',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 14:24:08',
                'updated_at' => '2024-09-16 14:24:08',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 143,
                'name' => 'Medi Advisor',
                'email' => 'medi@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 14:58:39',
                'password' => '$2y$10$/tfQuevJvHeT19cfGLY/ueWT1ArL4xvY2EirK8ApHLGJth4hgQgCa',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 14:58:39',
                'updated_at' => '2024-09-16 14:58:39',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 144,
                'name' => 'Gianna Health',
                'email' => 'Gianna@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 15:11:50',
                'password' => '$2y$10$5zFk.oBJ5TulEPFoZ9PMH./vcZerJVzWLOdgyn1CWf3xNjPlwhVx2',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 15:11:50',
                'updated_at' => '2024-09-16 15:11:50',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 145,
                'name' => 'Nathan wellness',
                'email' => 'nathan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 15:21:26',
                'password' => '$2y$10$OU3fSghq79xq.ESF37CNyewRWMjAn9dZVyGz9kFq4t6goygyjA1iC',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 15:21:26',
                'updated_at' => '2024-09-16 15:21:26',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 146,
                'name' => 'Health Advisor',
                'email' => 'advisor@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 15:37:40',
                'password' => '$2y$10$pyNyChBwkmZNaht/q3EuNe1JzLlhkWX6cWL/0ShYSLQS4A7e4Vj6G',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 15:37:40',
                'updated_at' => '2024-09-16 15:37:40',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 147,
                'name' => 'Aurora Leah',
                'email' => 'Aurora@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 16:18:08',
                'password' => '$2y$10$OXjTKahkpWvC/0zjT0J9ROmYfdlZ/metXrd9I.32W9pTM/aeqHo5a',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 16:18:08',
                'updated_at' => '2024-09-16 16:18:08',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 148,
                'name' => 'Dylan Cole',
                'email' => 'Dylan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 16:24:50',
                'password' => '$2y$10$qNMSVVHmPwH/ATTRz3wbl.8Hhr1UXQvPHqW67fOQOaw2MkXtF/PW.',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 16:24:50',
                'updated_at' => '2024-09-16 16:24:50',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 149,
                'name' => 'Savannah Ava',
                'email' => 'Savannah@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 16:30:44',
                'password' => '$2y$10$lG8ynIdToReg/p1z0DDxY.XNMQFhVp6wbBImc6rHeupELNB6uIU4y',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 16:30:44',
                'updated_at' => '2024-09-16 16:30:44',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 150,
                'name' => 'Natalie Ryan',
                'email' => 'Natalie@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 16:35:47',
                'password' => '$2y$10$tPwafr9QLHq0ihI5OOSmTO1w7rcqw/HapZ4JRjel2mYdvGeQRJ57K',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 16:35:47',
                'updated_at' => '2024-09-16 16:35:47',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 151,
                'name' => 'Emilia Lily',
                'email' => 'Emilia@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-16 17:17:54',
                'password' => '$2y$10$tIblFS0OQsBQtpqxYWNZSOSRYhpe9NigueZx.wvZGTh4jYaNd1V3m',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-16 17:17:54',
                'updated_at' => '2024-09-16 17:17:54',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 152,
                'name' => 'heta yor',
                'email' => 'hetayor645@marchub.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-19 15:58:41',
                'password' => '$2y$10$opsBPZBWmtpuLpl01nC1T.PLF93Az71Li0N4CQ3a9l5lc9zMdDfgu',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-19 15:58:41',
                'updated_at' => '2024-09-19 15:58:41',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 153,
                'name' => 'John Daniel',
                'email' => 'john1@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-25 12:42:44',
                'password' => '$2y$10$Gce5R9G.AVKrb4/n56md5Og7mYrtFkKQcYT1Uo84l1xITqn8zaUY6',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-25 12:42:44',
                'updated_at' => '2024-09-25 12:42:44',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 154,
                'name' => 'jofra lee',
                'email' => 'jofra@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-25 12:57:22',
                'password' => '$2y$10$JOk.K1ZezEGXUZI63gCfseux6wXgsw938jSBndWvc1et8Z.VtJ7Zi',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-25 12:57:22',
                'updated_at' => '2024-09-25 12:57:22',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 155,
                'name' => 'Jacque james',
                'email' => 'Jacque@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-25 13:02:57',
                'password' => '$2y$10$0e8rfr9UgBHSuPsDQybZNuH9LZSCYmS8sjxf6nlKUHzVxydvlSgyq',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-25 13:02:57',
                'updated_at' => '2024-09-25 13:02:57',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 156,
                'name' => 'ewdgs wertew',
                'email' => 'abc@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-26 11:11:09',
                'password' => '$2y$10$v.lE6vP7Qr5kKZBKk7twouWzfpIqBbiEtjM4N9mytrTUzW7VAdrs6',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-26 11:11:09',
                'updated_at' => '2024-09-26 11:11:09',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 157,
                'name' => 'kikk llikk',
                'email' => 'abc1@gmail.om',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-26 11:27:38',
                'password' => '$2y$10$HxhWdsbSPjtbgq3CtbpEf.hvXAG7y3KturcK/eRZRhmtXNaY0e1A2',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-26 11:27:38',
                'updated_at' => '2024-09-26 11:27:38',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 158,
                'name' => 'Patient Health',
                'email' => 'patient@health.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-26 11:34:21',
                'password' => '$2y$10$OYe2O5Mt3Y0W8k6haH9Fju4kbE4JJIQBk85FgFRMiSXkaDeRsaJUy',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-26 11:34:21',
                'updated_at' => '2024-09-26 11:34:21',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 159,
                'name' => 'aaaf dgsadga',
                'email' => 'abc2@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-26 13:17:21',
                'password' => '$2y$10$vqUXC1WRQb3OQYbNkrYosewAUABhjE.gVFAkxrtLCuIXMJwlNYLOi',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-26 13:17:21',
                'updated_at' => '2024-09-26 13:17:21',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 160,
                'name' => 'Bilal Naeem',
                'email' => 'bilal.invictus@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-27 15:02:28',
                'password' => '$2y$10$ihKWFC.4oJCpOUYWBN9BBOGsFNN7URkLSFfZTapycI4I2I.VhnRF2',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-27 15:02:28',
                'updated_at' => '2024-09-27 15:02:28',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 161,
                'name' => 'Bilal Naeem',
                'email' => 'mbilalnaeem5@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-27 15:04:50',
                'password' => '$2y$10$YNavYzZrcOZGQwBzI/w.b.qCd4zOqzEJG2JF46mApmXHWxuQbalvW',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-27 15:04:50',
                'updated_at' => '2024-10-01 15:03:21',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 162,
                'name' => 'Austin Smith',
                'email' => 'kanikuf@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-09-30 16:15:41',
                'password' => '$2y$10$PVpIzGEIv59zJXdMwe5N1uHqI8s3KGgvcFMLBLxaCxzboppLim7P.',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-09-30 16:14:39',
                'updated_at' => '2024-09-30 16:15:41',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 163,
                'name' => 'M Bilal Naeem',
                'email' => 'bilal.invictus1@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-01 15:04:26',
                'password' => '$2y$10$9HMke8WGDu7l8NsiufNnlun/BPuDW.rupLkVcatmf0S1vrc3IvCcq',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-01 15:04:26',
                'updated_at' => '2024-10-01 15:04:26',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 164,
                'name' => 'faizan fazal',
                'email' => 'faizan12@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-03 15:52:11',
                'password' => '$2y$10$c68eFlyY/MPEn7SAIr0izuLww5J8QakpgfuO6zuulGxWyEUlH2gSe',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-03 15:52:11',
                'updated_at' => '2024-10-03 15:52:11',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 165,
                'name' => 'Ria Morris',
                'email' => 'pafuf@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-03 18:02:55',
                'password' => '$2y$10$0FuEndqIfYB/4scWNnOOl.oqX434jirkdVBrO/CIC20ymDOYeGcIm',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-03 18:02:55',
                'updated_at' => '2024-10-03 18:02:55',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 166,
                'name' => 'Bilal Naeem',
                'email' => 'bilal@test.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-05 20:43:58',
                'password' => '$2y$10$npw7UIPu11wlVIA5kHvF7.qndLPQWJT69n4nkSWoW.3Rz/e6q/mfW',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-05 20:43:58',
                'updated_at' => '2024-10-05 20:43:58',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 167,
                'name' => 'bilal naeem',
                'email' => 'bilal@test2.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-05 20:57:55',
                'password' => '$2y$10$gMcZMvN6j7A3IBTkOhbtDeFaVpO91DxakGFET.7UmHlqERZy36w72',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-05 20:57:55',
                'updated_at' => '2024-10-05 20:57:55',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 168,
                'name' => 'Casey Gamble',
                'email' => 'gaximexe@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-07 12:06:49',
                'password' => '$2y$10$8WgLngeW7ywFqvwQl0vsWO.IU4XT7RDtNwOQjIUS.yoLMa9hOVzla',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-07 12:06:49',
                'updated_at' => '2024-10-07 12:06:49',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 169,
                'name' => 'Amanda Velazquez',
                'email' => 'lafaqup@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-07 12:56:28',
                'password' => '$2y$10$4jUaWZbcGb5loEWc.Fchs.zMBVJLm9UdaWvRX5BMyXjYVpYEv5amy',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-07 12:56:28',
                'updated_at' => '2024-10-07 12:56:28',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 170,
                'name' => 'Educational Advisor',
                'email' => 'patient1@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-07 17:33:39',
                'password' => '$2y$10$gqRLr5LIrHMcOuWC.2v1menJbyDw8XFDjkng.BMa0bbtCUE1yMfkK',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-07 17:33:39',
                'updated_at' => '2024-10-07 17:33:39',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 171,
                'name' => 'doctor1 asda',
                'email' => 'doctor1@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-07 17:37:38',
                'password' => '$2y$10$3u7mzsSRovqUMByZejeMb.4bwmSUF/3at/4pJwreaUw9C/BGEVX3i',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-07 17:37:38',
                'updated_at' => '2024-10-07 17:37:38',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 172,
                'name' => 'May Cooley',
                'email' => 'kycomekupa@mailinator.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2024-10-07 17:55:52',
                'password' => '$2y$10$D.4x9wXp0ZYmr.BLjD7AL.EjrhrCts8AtXdSFJu9qvqHraBOtXTKW',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2024-10-07 17:55:52',
                'updated_at' => '2024-10-07 17:55:52',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}